/**
 * \file
 * \brief Boost converter regulation and safety functions
 */
#include "boost.h"

/**
 * Duty cycle lookup-table. Generated by Python-script.
 */
const uint8_t PWM_LOOKUP[][2] PROGMEM = {
		{ 0x01, 0xc7 }, 	// Duty cycle = 1.00
		{ 0x01, 0xba }, 	// Duty cycle = 1.07
		{ 0x01, 0xaf }, 	// Duty cycle = 1.14
		{ 0x02, 0xf8 }, 	// Duty cycle = 1.20
		{ 0x02, 0xeb }, 	// Duty cycle = 1.27
		{ 0x02, 0xdf }, 	// Duty cycle = 1.34
		{ 0x02, 0xd4 }, 	// Duty cycle = 1.41
		{ 0x02, 0xcb }, 	// Duty cycle = 1.47
		{ 0x02, 0xc2 }, 	// Duty cycle = 1.54
		{ 0x02, 0xba }, 	// Duty cycle = 1.60
		{ 0x03, 0xee }, 	// Duty cycle = 1.67
		{ 0x03, 0xe5 }, 	// Duty cycle = 1.74
		{ 0x02, 0xa5 }, 	// Duty cycle = 1.81
		{ 0x02, 0x9f }, 	// Duty cycle = 1.88
		{ 0x03, 0xcd }, 	// Duty cycle = 1.94
		{ 0x04, 0xf8 }, 	// Duty cycle = 2.01
		{ 0x04, 0xf0 }, 	// Duty cycle = 2.07
		{ 0x02, 0x8b }, 	// Duty cycle = 2.14
		{ 0x03, 0xb4 }, 	// Duty cycle = 2.21
		{ 0x04, 0xda }, 	// Duty cycle = 2.28
		{ 0x02, 0x7f }, 	// Duty cycle = 2.34
		{ 0x05, 0xf8 }, 	// Duty cycle = 2.41
		{ 0x05, 0xf1 }, 	// Duty cycle = 2.48
		{ 0x05, 0xeb }, 	// Duty cycle = 2.54
		{ 0x03, 0x98 }, 	// Duty cycle = 2.61
		{ 0x05, 0xdf }, 	// Duty cycle = 2.68
		{ 0x06, 0xfe }, 	// Duty cycle = 2.75
		{ 0x06, 0xf8 }, 	// Duty cycle = 2.81
		{ 0x03, 0x8a }, 	// Duty cycle = 2.88
		{ 0x06, 0xec }, 	// Duty cycle = 2.95
		{ 0x04, 0xa5 }, 	// Duty cycle = 3.01
		{ 0x06, 0xe2 }, 	// Duty cycle = 3.08
		{ 0x07, 0xfd }, 	// Duty cycle = 3.15
		{ 0x07, 0xf7 }, 	// Duty cycle = 3.23
		{ 0x06, 0xd4 }, 	// Duty cycle = 3.29
		{ 0x07, 0xee }, 	// Duty cycle = 3.35
		{ 0x06, 0xcc }, 	// Duty cycle = 3.41
		{ 0x06, 0xc8 }, 	// Duty cycle = 3.48
		{ 0x05, 0xa8 }, 	// Duty cycle = 3.55
		{ 0x07, 0xdc }, 	// Duty cycle = 3.62
		{ 0x06, 0xbd }, 	// Duty cycle = 3.68
		{ 0x08, 0xef }, 	// Duty cycle = 3.75
		{ 0x04, 0x82 }, 	// Duty cycle = 3.82
		{ 0x07, 0xcd }, 	// Duty cycle = 3.88
		{ 0x09, 0xfc }, 	// Duty cycle = 3.95
		{ 0x08, 0xdf }, 	// Duty cycle = 4.02
		{ 0x08, 0xdb }, 	// Duty cycle = 4.09
		{ 0x09, 0xef }, 	// Duty cycle = 4.17
		{ 0x09, 0xec }, 	// Duty cycle = 4.22
		{ 0x09, 0xe8 }, 	// Duty cycle = 4.29
		{ 0x0a, 0xfb }, 	// Duty cycle = 4.37
		{ 0x09, 0xe1 }, 	// Duty cycle = 4.42
		{ 0x06, 0x9b }, 	// Duty cycle = 4.49
		{ 0x0a, 0xf0 }, 	// Duty cycle = 4.56
		{ 0x0a, 0xed }, 	// Duty cycle = 4.62
		{ 0x09, 0xd4 }, 	// Duty cycle = 4.69
		{ 0x0b, 0xfb }, 	// Duty cycle = 4.76
		{ 0x0a, 0xe3 }, 	// Duty cycle = 4.82
		{ 0x08, 0xb7 }, 	// Duty cycle = 4.89
		{ 0x0b, 0xf1 }, 	// Duty cycle = 4.96
		{ 0x09, 0xc6 }, 	// Duty cycle = 5.03
		{ 0x0a, 0xd7 }, 	// Duty cycle = 5.09
		{ 0x0c, 0xfb }, 	// Duty cycle = 5.16
		{ 0x07, 0x98 }, 	// Duty cycle = 5.23
		{ 0x08, 0xa9 }, 	// Duty cycle = 5.29
		{ 0x0a, 0xcc }, 	// Duty cycle = 5.37
		{ 0x06, 0x80 }, 	// Duty cycle = 5.43
		{ 0x09, 0xb5 }, 	// Duty cycle = 5.49
		{ 0x0d, 0xfa }, 	// Duty cycle = 5.58
		{ 0x0c, 0xe6 }, 	// Duty cycle = 5.63
		{ 0x08, 0x9d }, 	// Duty cycle = 5.70
		{ 0x0d, 0xf2 }, 	// Duty cycle = 5.76
		{ 0x0c, 0xde }, 	// Duty cycle = 5.83
		{ 0x0e, 0xfd }, 	// Duty cycle = 5.91
		{ 0x0c, 0xd9 }, 	// Duty cycle = 5.96
		{ 0x0b, 0xc6 }, 	// Duty cycle = 6.03
		{ 0x0e, 0xf5 }, 	// Duty cycle = 6.10
		{ 0x08, 0x91 }, 	// Duty cycle = 6.16
		{ 0x0e, 0xef }, 	// Duty cycle = 6.25
		{ 0x0f, 0xfd }, 	// Duty cycle = 6.30
		{ 0x09, 0x9c }, 	// Duty cycle = 6.37
		{ 0x0a, 0xaa }, 	// Duty cycle = 6.43
		{ 0x0c, 0xc7 }, 	// Duty cycle = 6.50
		{ 0x08, 0x88 }, 	// Duty cycle = 6.57
		{ 0x0d, 0xd2 }, 	// Duty cycle = 6.64
		{ 0x0c, 0xc1 }, 	// Duty cycle = 6.70
		{ 0x0c, 0xbf }, 	// Duty cycle = 6.77
		{ 0x0f, 0xe9 }, 	// Duty cycle = 6.84
		{ 0x10, 0xf5 }, 	// Duty cycle = 6.91
		{ 0x0e, 0xd6 }, 	// Duty cycle = 6.98
		{ 0x0e, 0xd4 }, 	// Duty cycle = 7.04
		{ 0x0c, 0xb6 }, 	// Duty cycle = 7.10
		{ 0x11, 0xfa }, 	// Duty cycle = 7.17
		{ 0x0a, 0x97 }, 	// Duty cycle = 7.24
		{ 0x0f, 0xda }, 	// Duty cycle = 7.31
		{ 0x0f, 0xd8 }, 	// Duty cycle = 7.37
		{ 0x11, 0xf1 }, 	// Duty cycle = 7.44
		{ 0x12, 0xfc }, 	// Duty cycle = 7.51
		{ 0x0e, 0xc5 }, 	// Duty cycle = 7.58
		{ 0x0a, 0x8f }, 	// Duty cycle = 7.64
		{ 0x12, 0xf5 }, 	// Duty cycle = 7.72
		{ 0x0d, 0xb3 }, 	// Duty cycle = 7.78
		{ 0x13, 0xfe }, 	// Duty cycle = 7.84
		{ 0x10, 0xd6 }, 	// Duty cycle = 7.91
		{ 0x0c, 0xa2 }, 	// Duty cycle = 7.98
		{ 0x0d, 0xad }, 	// Duty cycle = 8.05
		{ 0x12, 0xe9 }, 	// Duty cycle = 8.12
		{ 0x0c, 0x9e }, 	// Duty cycle = 8.18
		{ 0x0f, 0xc1 }, 	// Duty cycle = 8.25
		{ 0x14, 0xfb }, 	// Duty cycle = 8.33
		{ 0x0f, 0xbe }, 	// Duty cycle = 8.38
		{ 0x12, 0xe0 }, 	// Duty cycle = 8.44
		{ 0x13, 0xea }, 	// Duty cycle = 8.51
		{ 0x13, 0xe8 }, 	// Duty cycle = 8.58
		{ 0x0f, 0xb8 }, 	// Duty cycle = 8.65
		{ 0x14, 0xf0 }, 	// Duty cycle = 8.71
		{ 0x11, 0xcc }, 	// Duty cycle = 8.78
		{ 0x13, 0xe1 }, 	// Duty cycle = 8.85
		{ 0x0d, 0x9c }, 	// Duty cycle = 8.92
		{ 0x0e, 0xa6 }, 	// Duty cycle = 8.98
		{ 0x12, 0xd1 }, 	// Duty cycle = 9.05
		{ 0x16, 0xfb }, 	// Duty cycle = 9.13
		{ 0x11, 0xc3 }, 	// Duty cycle = 9.18
		{ 0x0f, 0xac }, 	// Duty cycle = 9.25
		{ 0x0e, 0xa0 }, 	// Duty cycle = 9.32
		{ 0x16, 0xf4 }, 	// Duty cycle = 9.39
		{ 0x12, 0xc8 }, 	// Duty cycle = 9.45
		{ 0x17, 0xfb }, 	// Duty cycle = 9.52
		{ 0x14, 0xda }, 	// Duty cycle = 9.59
		{ 0x0d, 0x90 }, 	// Duty cycle = 9.66
		{ 0x14, 0xd7 }, 	// Duty cycle = 9.72
		{ 0x16, 0xea }, 	// Duty cycle = 9.79
		{ 0x13, 0xca }, 	// Duty cycle = 9.85
		{ 0x18, 0xfb }, 	// Duty cycle = 9.92
		{ 0x18, 0xf9 }, 	// Duty cycle = 10.00
		{ 0x12, 0xbc }, 	// Duty cycle = 10.05
		{ 0x18, 0xf6 }, 	// Duty cycle = 10.12
		{ 0x0f, 0x9c }, 	// Duty cycle = 10.19
		{ 0x17, 0xe9 }, 	// Duty cycle = 10.26
		{ 0x0f, 0x9a }, 	// Duty cycle = 10.32
		{ 0x17, 0xe6 }, 	// Duty cycle = 10.39
		{ 0x0f, 0x98 }, 	// Duty cycle = 10.46
		{ 0x19, 0xf6 }, 	// Duty cycle = 10.53
		{ 0x18, 0xeb }, 	// Duty cycle = 10.59
		{ 0x14, 0xc4 }, 	// Duty cycle = 10.66
		{ 0x18, 0xe8 }, 	// Duty cycle = 10.73
		{ 0x0e, 0x8a }, 	// Duty cycle = 10.79
		{ 0x17, 0xdc }, 	// Duty cycle = 10.86
		{ 0x13, 0xb6 }, 	// Duty cycle = 10.93
		{ 0x14, 0xbe }, 	// Duty cycle = 10.99
		{ 0x17, 0xd8 }, 	// Duty cycle = 11.06
		{ 0x1b, 0xfa }, 	// Duty cycle = 11.16
		{ 0x0e, 0x85 }, 	// Duty cycle = 11.19
		{ 0x18, 0xdd }, 	// Duty cycle = 11.26
		{ 0x16, 0xca }, 	// Duty cycle = 11.33
		{ 0x15, 0xc0 }, 	// Duty cycle = 11.40
		{ 0x1c, 0xfc }, 	// Duty cycle = 11.46
		{ 0x1a, 0xe9 }, 	// Duty cycle = 11.54
		{ 0x1c, 0xf9 }, 	// Duty cycle = 11.60
		{ 0x1b, 0xef }, 	// Duty cycle = 11.67
		{ 0x14, 0xb2 }, 	// Duty cycle = 11.73
		{ 0x14, 0xb1 }, 	// Duty cycle = 11.80
		{ 0x1b, 0xeb }, 	// Duty cycle = 11.86
		{ 0x14, 0xaf }, 	// Duty cycle = 11.93
		{ 0x1d, 0xf9 }, 	// Duty cycle = 12.00
		{ 0x1b, 0xe7 }, 	// Duty cycle = 12.07
		{ 0x1c, 0xee }, 	// Duty cycle = 12.13
		{ 0x1e, 0xfd }, 	// Duty cycle = 12.20
		{ 0x13, 0xa2 }, 	// Duty cycle = 12.27
		{ 0x1b, 0xe2 }, 	// Duty cycle = 12.33
		{ 0x1e, 0xf9 }, 	// Duty cycle = 12.40
		{ 0x1e, 0xf7 }, 	// Duty cycle = 12.50
		{ 0x1f, 0xfe }, 	// Duty cycle = 12.55
		{ 0x1e, 0xf5 }, 	// Duty cycle = 12.60
		{ 0x1b, 0xdc }, 	// Duty cycle = 12.67
		{ 0x1a, 0xd3 }, 	// Duty cycle = 12.74
		{ 0x14, 0xa3 }, 	// Duty cycle = 12.80
		{ 0x19, 0xc9 }, 	// Duty cycle = 12.87
		{ 0x20, 0xfe }, 	// Duty cycle = 12.94
		{ 0x1c, 0xde }, 	// Duty cycle = 13.00
		{ 0x13, 0x98 }, 	// Duty cycle = 13.07
		{ 0x11, 0x88 }, 	// Duty cycle = 13.14
		{ 0x1b, 0xd3 }, 	// Duty cycle = 13.21
		{ 0x1d, 0xe1 }, 	// Duty cycle = 13.27
		{ 0x20, 0xf6 }, 	// Duty cycle = 13.36
		{ 0x17, 0xb2 }, 	// Duty cycle = 13.41
		{ 0x12, 0x8c }, 	// Duty cycle = 13.48
		{ 0x19, 0xbf }, 	// Duty cycle = 13.54
		{ 0x16, 0xa8 }, 	// Duty cycle = 13.61
		{ 0x1f, 0xe9 }, 	// Duty cycle = 13.68
		{ 0x1c, 0xd2 }, 	// Duty cycle = 13.74
		{ 0x1c, 0xd1 }, 	// Duty cycle = 13.81
		{ 0x1c, 0xd0 }, 	// Duty cycle = 13.88
		{ 0x1c, 0xcf }, 	// Duty cycle = 13.94
		{ 0x1c, 0xce }, 	// Duty cycle = 14.01
		{ 0x1c, 0xcd }, 	// Duty cycle = 14.08
		{ 0x1c, 0xcc }, 	// Duty cycle = 14.15
		{ 0x1a, 0xbd }, 	// Duty cycle = 14.21
		{ 0x23, 0xfb }, 	// Duty cycle = 14.29
		{ 0x21, 0xec }, 	// Duty cycle = 14.35
		{ 0x1f, 0xdd }, 	// Duty cycle = 14.41
		{ 0x1f, 0xdc }, 	// Duty cycle = 14.48
		{ 0x1e, 0xd4 }, 	// Duty cycle = 14.55
		{ 0x12, 0x81 }, 	// Duty cycle = 14.62
		{ 0x24, 0xfb }, 	// Duty cycle = 14.68
		{ 0x23, 0xf3 }, 	// Duty cycle = 14.75
		{ 0x23, 0xf2 }, 	// Duty cycle = 14.81
		{ 0x18, 0xa7 }, 	// Duty cycle = 14.88
		{ 0x1c, 0xc1 }, 	// Duty cycle = 14.95
		{ 0x25, 0xfc }, 	// Duty cycle = 15.02
		{ 0x1a, 0xb2 }, 	// Duty cycle = 15.08
		{ 0x22, 0xe6 }, 	// Duty cycle = 15.15
		{ 0x22, 0xe5 }, 	// Duty cycle = 15.22
		{ 0x22, 0xe4 }, 	// Duty cycle = 15.28
		{ 0x22, 0xe3 }, 	// Duty cycle = 15.35
		{ 0x22, 0xe2 }, 	// Duty cycle = 15.42
		{ 0x22, 0xe1 }, 	// Duty cycle = 15.49
		{ 0x22, 0xe0 }, 	// Duty cycle = 15.56
		{ 0x22, 0xdf }, 	// Duty cycle = 15.62
		{ 0x27, 0xfe }, 	// Duty cycle = 15.69
		{ 0x16, 0x91 }, 	// Duty cycle = 15.75
		{ 0x18, 0x9d }, 	// Duty cycle = 15.82
		{ 0x21, 0xd5 }, 	// Duty cycle = 15.89
		{ 0x1d, 0xbb }, 	// Duty cycle = 15.96
		{ 0x1c, 0xb4 }, 	// Duty cycle = 16.02
		{ 0x1b, 0xad }, 	// Duty cycle = 16.09
		{ 0x24, 0xe4 }, 	// Duty cycle = 16.16
		{ 0x24, 0xe3 }, 	// Duty cycle = 16.23
		{ 0x23, 0xdc }, 	// Duty cycle = 16.29
		{ 0x23, 0xdb }, 	// Duty cycle = 16.36
		{ 0x21, 0xce }, 	// Duty cycle = 16.43
		{ 0x1f, 0xc1 }, 	// Duty cycle = 16.49
		{ 0x19, 0x9c }, 	// Duty cycle = 16.56
		{ 0x29, 0xfb }, 	// Duty cycle = 16.67
		{ 0x29, 0xfa }, 	// Duty cycle = 16.73
		{ 0x1d, 0xb2 }, 	// Duty cycle = 16.76
		{ 0x22, 0xcf }, 	// Duty cycle = 16.83
		{ 0x24, 0xda }, 	// Duty cycle = 16.89
		{ 0x25, 0xdf }, 	// Duty cycle = 16.96
		{ 0x26, 0xe4 }, 	// Duty cycle = 17.03
		{ 0x27, 0xe9 }, 	// Duty cycle = 17.09
		{ 0x16, 0x85 }, 	// Duty cycle = 17.16
		{ 0x27, 0xe7 }, 	// Duty cycle = 17.24
		{ 0x1f, 0xb8 }, 	// Duty cycle = 17.30
		{ 0x1c, 0xa6 }, 	// Duty cycle = 17.37
		{ 0x25, 0xd9 }, 	// Duty cycle = 17.43
		{ 0x29, 0xef }, 	// Duty cycle = 17.50
		{ 0x26, 0xdd }, 	// Duty cycle = 17.57
		{ 0x2c, 0xfe }, 	// Duty cycle = 17.65
		{ 0x27, 0xe1 }, 	// Duty cycle = 17.70
		{ 0x22, 0xc4 }, 	// Duty cycle = 17.77
		{ 0x1b, 0x9c }, 	// Duty cycle = 17.83
		{ 0x1c, 0xa1 }, 	// Duty cycle = 17.90
		{ 0x16, 0x7f }, 	// Duty cycle = 17.97
		{ 0x2b, 0xf3 }, 	// Duty cycle = 18.03
		{ 0x29, 0xe7 }, 	// Duty cycle = 18.10
		{ 0x2d, 0xfc }, 	// Duty cycle = 18.18
		{ 0x1e, 0xa9 }, 	// Duty cycle = 18.24
		{ 0x28, 0xdf }, 	// Duty cycle = 18.30
		{ 0x2a, 0xe9 }, 	// Duty cycle = 18.38
		{ 0x20, 0xb2 }, 	// Duty cycle = 18.44
		{ 0x29, 0xe2 }, 	// Duty cycle = 18.50
		{ 0x26, 0xd1 }, 	// Duty cycle = 18.57
		{ 0x28, 0xdb }, 	// Duty cycle = 18.64
		{ 0x19, 0x8a }, 	// Duty cycle = 18.71
		{ 0x2d, 0xf4 }, 	// Duty cycle = 18.78
		{ 0x26, 0xce }, 	// Duty cycle = 18.84
		{ 0x25, 0xc8 }, 	// Duty cycle = 18.91
		{ 0x2f, 0xfc }, 	// Duty cycle = 18.97
		{ 0x2f, 0xfb }, 	// Duty cycle = 19.05
		{ 0x2e, 0xf5 }, 	// Duty cycle = 19.11
		{ 0x29, 0xda }, 	// Duty cycle = 19.18
		{ 0x2d, 0xee }, 	// Duty cycle = 19.25
		{ 0x26, 0xc9 }, 	// Duty cycle = 19.31
		{ 0x1e, 0x9f }, 	// Duty cycle = 19.38
		{ 0x30, 0xfb }, 	// Duty cycle = 19.44
		{ 0x2f, 0xf5 }, 	// Duty cycle = 19.51
		{ 0x24, 0xbc }, 	// Duty cycle = 19.58
		{ 0x2b, 0xdf }, 	// Duty cycle = 19.64
		{ 0x28, 0xcf }, 	// Duty cycle = 19.71
		{ 0x23, 0xb5 }, 	// Duty cycle = 19.78
		{ 0x19, 0x82 }, 	// Duty cycle = 19.85
		{ 0x2c, 0xe1 }, 	// Duty cycle = 19.91
		{ 0x32, 0xfe }, 	// Duty cycle = 20.00
		{ 0x32, 0xfd }, 	// Duty cycle = 20.08
		{ 0x23, 0xb2 }, 	// Duty cycle = 20.11
		{ 0x2c, 0xde }, 	// Duty cycle = 20.18
		{ 0x30, 0xf1 }, 	// Duty cycle = 20.25
		{ 0x32, 0xfa }, 	// Duty cycle = 20.32
		{ 0x1f, 0x9c }, 	// Duty cycle = 20.38
		{ 0x2c, 0xdb }, 	// Duty cycle = 20.45
		{ 0x2e, 0xe4 }, 	// Duty cycle = 20.52
		{ 0x30, 0xed }, 	// Duty cycle = 20.59
		{ 0x25, 0xb7 }, 	// Duty cycle = 20.65
		{ 0x33, 0xfa }, 	// Duty cycle = 20.72
		{ 0x34, 0xfe }, 	// Duty cycle = 20.78
		{ 0x30, 0xea }, 	// Duty cycle = 20.85
		{ 0x28, 0xc3 }, 	// Duty cycle = 20.92
		{ 0x32, 0xf2 }, 	// Duty cycle = 20.99
		{ 0x33, 0xf6 }, 	// Duty cycle = 21.05
		{ 0x21, 0xa0 }, 	// Duty cycle = 21.12
		{ 0x31, 0xeb }, 	// Duty cycle = 21.19
		{ 0x2b, 0xce }, 	// Duty cycle = 21.26
		{ 0x29, 0xc4 }, 	// Duty cycle = 21.32
		{ 0x24, 0xac }, 	// Duty cycle = 21.39
		{ 0x34, 0xf6 }, 	// Duty cycle = 21.46
		{ 0x2f, 0xde }, 	// Duty cycle = 21.52
		{ 0x25, 0xaf }, 	// Duty cycle = 21.59
		{ 0x21, 0x9c }, 	// Duty cycle = 21.66
		{ 0x34, 0xf3 }, 	// Duty cycle = 21.72
		{ 0x32, 0xe9 }, 	// Duty cycle = 21.79
		{ 0x27, 0xb6 }, 	// Duty cycle = 21.86
		{ 0x28, 0xba }, 	// Duty cycle = 21.93
		{ 0x29, 0xbe }, 	// Duty cycle = 21.99
		{ 0x2c, 0xcb }, 	// Duty cycle = 22.06
		{ 0x31, 0xe1 }, 	// Duty cycle = 22.12
		{ 0x37, 0xfb }, 	// Duty cycle = 22.22
		{ 0x36, 0xf6 }, 	// Duty cycle = 22.27
		{ 0x2f, 0xd6 }, 	// Duty cycle = 22.33
		{ 0x2a, 0xbf }, 	// Duty cycle = 22.40
		{ 0x29, 0xba }, 	// Duty cycle = 22.46
		{ 0x28, 0xb5 }, 	// Duty cycle = 22.53
		{ 0x35, 0xee }, 	// Duty cycle = 22.59
		{ 0x2d, 0xca }, 	// Duty cycle = 22.66
		{ 0x36, 0xf1 }, 	// Duty cycle = 22.73
		{ 0x1e, 0x87 }, 	// Duty cycle = 22.79
		{ 0x32, 0xde }, 	// Duty cycle = 22.87
		{ 0x23, 0x9c }, 	// Duty cycle = 22.93
		{ 0x2d, 0xc7 }, 	// Duty cycle = 23.00
		{ 0x38, 0xf6 }, 	// Duty cycle = 23.08
		{ 0x21, 0x92 }, 	// Duty cycle = 23.13
		{ 0x39, 0xf9 }, 	// Duty cycle = 23.20
		{ 0x38, 0xf4 }, 	// Duty cycle = 23.27
		{ 0x37, 0xef }, 	// Duty cycle = 23.33
		{ 0x36, 0xea }, 	// Duty cycle = 23.40
		{ 0x2d, 0xc3 }, 	// Duty cycle = 23.47
		{ 0x38, 0xf1 }, 	// Duty cycle = 23.55
		{ 0x3a, 0xf9 }, 	// Duty cycle = 23.60
		{ 0x27, 0xa8 }, 	// Duty cycle = 23.67
		{ 0x2e, 0xc5 }, 	// Duty cycle = 23.74
		{ 0x3b, 0xfb }, 	// Duty cycle = 23.81
		{ 0x39, 0xf2 }, 	// Duty cycle = 23.87
		{ 0x2c, 0xbb }, 	// Duty cycle = 23.94
		{ 0x3c, 0xfd }, 	// Duty cycle = 24.02
		{ 0x33, 0xd7 }, 	// Duty cycle = 24.07
		{ 0x37, 0xe7 }, 	// Duty cycle = 24.14
		{ 0x25, 0x9c }, 	// Duty cycle = 24.20
		{ 0x31, 0xcd }, 	// Duty cycle = 24.27
		{ 0x36, 0xe1 }, 	// Duty cycle = 24.34
		{ 0x28, 0xa7 }, 	// Duty cycle = 24.40
		{ 0x39, 0xec }, 	// Duty cycle = 24.47
		{ 0x27, 0xa2 }, 	// Duty cycle = 24.54
		{ 0x2e, 0xbe }, 	// Duty cycle = 24.61
		{ 0x38, 0xe6 }, 	// Duty cycle = 24.68
		{ 0x2f, 0xc1 }, 	// Duty cycle = 24.74
		{ 0x1f, 0x80 }, 	// Duty cycle = 24.81
		{ 0x30, 0xc4 }, 	// Duty cycle = 24.87
		{ 0x3e, 0xfb }, 	// Duty cycle = 25.00
		{ 0x3f, 0xfe }, 	// Duty cycle = 25.10
		{ 0x3f, 0xfe }, 	// Duty cycle = 25.10
		{ 0x2b, 0xae }, 	// Duty cycle = 25.14
		{ 0x3b, 0xed }, 	// Duty cycle = 25.21
		{ 0x2c, 0xb1 }, 	// Duty cycle = 25.28
		{ 0x24, 0x91 }, 	// Duty cycle = 25.34
		{ 0x3d, 0xf3 }, 	// Duty cycle = 25.41
		{ 0x27, 0x9c }, 	// Duty cycle = 25.48
		{ 0x2e, 0xb7 }, 	// Duty cycle = 25.54
		{ 0x33, 0xca }, 	// Duty cycle = 25.62
		{ 0x2e, 0xb6 }, 	// Duty cycle = 25.68
		{ 0x2a, 0xa6 }, 	// Duty cycle = 25.75
		{ 0x3e, 0xf3 }, 	// Duty cycle = 25.82
		{ 0x41, 0xfe }, 	// Duty cycle = 25.88
		{ 0x2f, 0xb8 }, 	// Duty cycle = 25.95
		{ 0x3f, 0xf5 }, 	// Duty cycle = 26.02
		{ 0x41, 0xfc }, 	// Duty cycle = 26.09
		{ 0x38, 0xd9 }, 	// Duty cycle = 26.15
		{ 0x2a, 0xa3 }, 	// Duty cycle = 26.22
		{ 0x28, 0x9b }, 	// Duty cycle = 26.28
		{ 0x26, 0x93 }, 	// Duty cycle = 26.35
		{ 0x37, 0xd3 }, 	// Duty cycle = 26.42
		{ 0x42, 0xfc }, 	// Duty cycle = 26.48
		{ 0x2e, 0xb0 }, 	// Duty cycle = 26.55
		{ 0x24, 0x8a }, 	// Duty cycle = 26.62
		{ 0x42, 0xfa }, 	// Duty cycle = 26.69
		{ 0x29, 0x9c }, 	// Duty cycle = 26.75
		{ 0x3a, 0xdb }, 	// Duty cycle = 26.82
		{ 0x38, 0xd3 }, 	// Duty cycle = 26.89
		{ 0x3d, 0xe5 }, 	// Duty cycle = 26.96
		{ 0x3b, 0xdd }, 	// Duty cycle = 27.03
		{ 0x43, 0xfa }, 	// Duty cycle = 27.09
		{ 0x3e, 0xe7 }, 	// Duty cycle = 27.16
		{ 0x30, 0xb3 }, 	// Duty cycle = 27.22
		{ 0x43, 0xf8 }, 	// Duty cycle = 27.31
		{ 0x3c, 0xde }, 	// Duty cycle = 27.35
		{ 0x40, 0xec }, 	// Duty cycle = 27.43
		{ 0x39, 0xd2 }, 	// Duty cycle = 27.49
		{ 0x3d, 0xe0 }, 	// Duty cycle = 27.56
		{ 0x31, 0xb4 }, 	// Duty cycle = 27.62
		{ 0x35, 0xc2 }, 	// Duty cycle = 27.69
		{ 0x45, 0xfb }, 	// Duty cycle = 27.78
		{ 0x3f, 0xe5 }, 	// Duty cycle = 27.83
		{ 0x28, 0x92 }, 	// Duty cycle = 27.89
		{ 0x3a, 0xd2 }, 	// Duty cycle = 27.96
		{ 0x2b, 0x9c }, 	// Duty cycle = 28.03
		{ 0x3a, 0xd1 }, 	// Duty cycle = 28.10
		{ 0x30, 0xad }, 	// Duty cycle = 28.16
		{ 0x45, 0xf7 }, 	// Duty cycle = 28.23
		{ 0x39, 0xcc }, 	// Duty cycle = 28.29
		{ 0x3a, 0xcf }, 	// Duty cycle = 28.37
		{ 0x39, 0xcb }, 	// Duty cycle = 28.43
		{ 0x34, 0xb9 }, 	// Duty cycle = 28.49
		{ 0x47, 0xfb }, 	// Duty cycle = 28.57
		{ 0x46, 0xf7 }, 	// Duty cycle = 28.63
		{ 0x41, 0xe5 }, 	// Duty cycle = 28.70
		{ 0x3e, 0xda }, 	// Duty cycle = 28.77
		{ 0x2e, 0xa2 }, 	// Duty cycle = 28.83
		{ 0x3e, 0xd9 }, 	// Duty cycle = 28.90
		{ 0x29, 0x90 }, 	// Duty cycle = 28.97
		{ 0x47, 0xf7 }, 	// Duty cycle = 29.03
		{ 0x46, 0xf3 }, 	// Duty cycle = 29.10
		{ 0x45, 0xef }, 	// Duty cycle = 29.17
		{ 0x44, 0xeb }, 	// Duty cycle = 29.24
		{ 0x2d, 0x9c }, 	// Duty cycle = 29.30
		{ 0x29, 0x8e }, 	// Duty cycle = 29.37
		{ 0x48, 0xf7 }, 	// Duty cycle = 29.44
		{ 0x3a, 0xc7 }, 	// Duty cycle = 29.50
		{ 0x36, 0xb9 }, 	// Duty cycle = 29.57
		{ 0x4a, 0xfc }, 	// Duty cycle = 29.64
		{ 0x3b, 0xc9 }, 	// Duty cycle = 29.70
		{ 0x26, 0x82 }, 	// Duty cycle = 29.77
		{ 0x49, 0xf7 }, 	// Duty cycle = 29.84
		{ 0x3c, 0xcb }, 	// Duty cycle = 29.90
		{ 0x4a, 0xf9 }, 	// Duty cycle = 30.00
		{ 0x4b, 0xfc }, 	// Duty cycle = 30.04
		{ 0x37, 0xb9 }, 	// Duty cycle = 30.11
		{ 0x45, 0xe7 }, 	// Duty cycle = 30.17
		{ 0x4a, 0xf7 }, 	// Duty cycle = 30.24
		{ 0x4c, 0xfd }, 	// Duty cycle = 30.31
		{ 0x40, 0xd5 }, 	// Duty cycle = 30.37
		{ 0x49, 0xf2 }, 	// Duty cycle = 30.45
		{ 0x47, 0xeb }, 	// Duty cycle = 30.51
		{ 0x2f, 0x9c }, 	// Duty cycle = 30.57
		{ 0x4b, 0xf7 }, 	// Duty cycle = 30.65
		{ 0x4d, 0xfd }, 	// Duty cycle = 30.71
		{ 0x4c, 0xf9 }, 	// Duty cycle = 30.80
		{ 0x41, 0xd5 }, 	// Duty cycle = 30.84
		{ 0x43, 0xdb }, 	// Duty cycle = 30.91
		{ 0x38, 0xb7 }, 	// Duty cycle = 30.98
		{ 0x4c, 0xf7 }, 	// Duty cycle = 31.05
		{ 0x45, 0xe0 }, 	// Duty cycle = 31.11
		{ 0x34, 0xa9 }, 	// Duty cycle = 31.18
		{ 0x4a, 0xef }, 	// Duty cycle = 31.25
		{ 0x3d, 0xc5 }, 	// Duty cycle = 31.31
		{ 0x4a, 0xee }, 	// Duty cycle = 31.38
		{ 0x31, 0x9e }, 	// Duty cycle = 31.45
		{ 0x4a, 0xed }, 	// Duty cycle = 31.51
		{ 0x4d, 0xf6 }, 	// Duty cycle = 31.58
		{ 0x4a, 0xec }, 	// Duty cycle = 31.65
		{ 0x47, 0xe2 }, 	// Duty cycle = 31.72
		{ 0x4a, 0xeb }, 	// Duty cycle = 31.78
		{ 0x31, 0x9c }, 	// Duty cycle = 31.85
		{ 0x4a, 0xea }, 	// Duty cycle = 31.91
		{ 0x46, 0xdd }, 	// Duty cycle = 31.98
		{ 0x4a, 0xe9 }, 	// Duty cycle = 32.05
		{ 0x2b, 0x88 }, 	// Duty cycle = 32.12
		{ 0x37, 0xad }, 	// Duty cycle = 32.18
		{ 0x4f, 0xf7 }, 	// Duty cycle = 32.26
		{ 0x34, 0xa3 }, 	// Duty cycle = 32.32
		{ 0x38, 0xaf }, 	// Duty cycle = 32.39
		{ 0x30, 0x96 }, 	// Duty cycle = 32.45
		{ 0x4f, 0xf5 }, 	// Duty cycle = 32.52
		{ 0x39, 0xb1 }, 	// Duty cycle = 32.58
		{ 0x4f, 0xf4 }, 	// Duty cycle = 32.65
		{ 0x46, 0xd8 }, 	// Duty cycle = 32.72
		{ 0x4f, 0xf3 }, 	// Duty cycle = 32.79
		{ 0x44, 0xd1 }, 	// Duty cycle = 32.86
		{ 0x4f, 0xf2 }, 	// Duty cycle = 32.92
		{ 0x3f, 0xc1 }, 	// Duty cycle = 32.99
		{ 0x4e, 0xee }, 	// Duty cycle = 33.05
		{ 0x33, 0x9c }, 	// Duty cycle = 33.12
		{ 0x4b, 0xe4 }, 	// Duty cycle = 33.19
		{ 0x54, 0xfe }, 	// Duty cycle = 33.33
		{ 0x54, 0xfe }, 	// Duty cycle = 33.33
		{ 0x54, 0xfd }, 	// Duty cycle = 33.46
		{ 0x54, 0xfd }, 	// Duty cycle = 33.46
		{ 0x39, 0xac }, 	// Duty cycle = 33.53
		{ 0x2a, 0x7f }, 	// Duty cycle = 33.59
		{ 0x44, 0xcc }, 	// Duty cycle = 33.66
		{ 0x55, 0xfe }, 	// Duty cycle = 33.73
		{ 0x30, 0x90 }, 	// Duty cycle = 33.79
		{ 0x55, 0xfd }, 	// Duty cycle = 33.86
		{ 0x4b, 0xdf }, 	// Duty cycle = 33.93
		{ 0x54, 0xf9 }, 	// Duty cycle = 34.00
		{ 0x4d, 0xe4 }, 	// Duty cycle = 34.06
		{ 0x55, 0xfb }, 	// Duty cycle = 34.13
		{ 0x34, 0x9a }, 	// Duty cycle = 34.19
		{ 0x55, 0xfa }, 	// Duty cycle = 34.26
		{ 0x44, 0xc8 }, 	// Duty cycle = 34.33
		{ 0x35, 0x9c }, 	// Duty cycle = 34.39
		{ 0x3c, 0xb0 }, 	// Duty cycle = 34.46
		{ 0x4c, 0xde }, 	// Duty cycle = 34.53
		{ 0x48, 0xd2 }, 	// Duty cycle = 34.60
		{ 0x4d, 0xe0 }, 	// Duty cycle = 34.67
		{ 0x39, 0xa6 }, 	// Duty cycle = 34.73
		{ 0x56, 0xf9 }, 	// Duty cycle = 34.80
		{ 0x34, 0x97 }, 	// Duty cycle = 34.87
		{ 0x32, 0x91 }, 	// Duty cycle = 34.93
		{ 0x53, 0xef }, 	// Duty cycle = 35.00
		{ 0x49, 0xd2 }, 	// Duty cycle = 35.07
		{ 0x4d, 0xdd }, 	// Duty cycle = 35.14
		{ 0x57, 0xf9 }, 	// Duty cycle = 35.20
		{ 0x4e, 0xdf }, 	// Duty cycle = 35.27
		{ 0x2e, 0x84 }, 	// Duty cycle = 35.34
		{ 0x38, 0xa0 }, 	// Duty cycle = 35.40
		{ 0x47, 0xca }, 	// Duty cycle = 35.47
		{ 0x55, 0xf1 }, 	// Duty cycle = 35.54
		{ 0x43, 0xbe }, 	// Duty cycle = 35.60
		{ 0x3c, 0xaa }, 	// Duty cycle = 35.67
		{ 0x58, 0xf8 }, 	// Duty cycle = 35.74
		{ 0x51, 0xe4 }, 	// Duty cycle = 35.81
		{ 0x4f, 0xde }, 	// Duty cycle = 35.87
		{ 0x44, 0xbf }, 	// Duty cycle = 35.94
		{ 0x54, 0xeb }, 	// Duty cycle = 36.02
		{ 0x4e, 0xda }, 	// Duty cycle = 36.07
		{ 0x48, 0xc9 }, 	// Duty cycle = 36.14
		{ 0x53, 0xe7 }, 	// Duty cycle = 36.21
		{ 0x49, 0xcb }, 	// Duty cycle = 36.27
		{ 0x5b, 0xfc }, 	// Duty cycle = 36.36
		{ 0x4a, 0xcd }, 	// Duty cycle = 36.41
		{ 0x58, 0xf3 }, 	// Duty cycle = 36.48
		{ 0x5a, 0xf8 }, 	// Duty cycle = 36.55
		{ 0x42, 0xb6 }, 	// Duty cycle = 36.61
		{ 0x53, 0xe4 }, 	// Duty cycle = 36.68
		{ 0x4e, 0xd6 }, 	// Duty cycle = 36.74
		{ 0x3b, 0xa2 }, 	// Duty cycle = 36.81
		{ 0x33, 0x8c }, 	// Duty cycle = 36.88
		{ 0x4a, 0xca }, 	// Duty cycle = 36.95
		{ 0x38, 0x99 }, 	// Duty cycle = 37.01
		{ 0x41, 0xb1 }, 	// Duty cycle = 37.08
		{ 0x5d, 0xfc }, 	// Duty cycle = 37.15
		{ 0x52, 0xde }, 	// Duty cycle = 37.22
		{ 0x54, 0xe3 }, 	// Duty cycle = 37.28
		{ 0x5c, 0xf8 }, 	// Duty cycle = 37.35
		{ 0x36, 0x92 }, 	// Duty cycle = 37.41
		{ 0x5c, 0xf7 }, 	// Duty cycle = 37.50
		{ 0x5e, 0xfc }, 	// Duty cycle = 37.55
		{ 0x51, 0xd9 }, 	// Duty cycle = 37.61
		{ 0x4d, 0xce }, 	// Duty cycle = 37.68
		{ 0x38, 0x96 }, 	// Duty cycle = 37.75
		{ 0x59, 0xed }, 	// Duty cycle = 37.82
		{ 0x55, 0xe2 }, 	// Duty cycle = 37.89
		{ 0x3e, 0xa5 }, 	// Duty cycle = 37.95
		{ 0x5b, 0xf1 }, 	// Duty cycle = 38.02
		{ 0x5f, 0xfb }, 	// Duty cycle = 38.10
		{ 0x41, 0xac }, 	// Duty cycle = 38.15
		{ 0x48, 0xbe }, 	// Duty cycle = 38.22
		{ 0x42, 0xae }, 	// Duty cycle = 38.29
		{ 0x53, 0xda }, 	// Duty cycle = 38.36
		{ 0x48, 0xbd }, 	// Duty cycle = 38.42
		{ 0x60, 0xfb }, 	// Duty cycle = 38.49
		{ 0x5f, 0xf8 }, 	// Duty cycle = 38.55
		{ 0x37, 0x90 }, 	// Duty cycle = 38.62
		{ 0x40, 0xa7 }, 	// Duty cycle = 38.69
		{ 0x50, 0xd0 }, 	// Duty cycle = 38.76
		{ 0x62, 0xfe }, 	// Duty cycle = 38.82
		{ 0x61, 0xfb }, 	// Duty cycle = 38.89
		{ 0x60, 0xf8 }, 	// Duty cycle = 38.96
		{ 0x5f, 0xf5 }, 	// Duty cycle = 39.02
		{ 0x55, 0xdb }, 	// Duty cycle = 39.09
		{ 0x40, 0xa5 }, 	// Duty cycle = 39.16
		{ 0x5a, 0xe7 }, 	// Duty cycle = 39.22
		{ 0x59, 0xe4 }, 	// Duty cycle = 39.30
		{ 0x61, 0xf8 }, 	// Duty cycle = 39.36
		{ 0x44, 0xae }, 	// Duty cycle = 39.43
		{ 0x5d, 0xed }, 	// Duty cycle = 39.50
		{ 0x47, 0xb5 }, 	// Duty cycle = 39.56
		{ 0x55, 0xd8 }, 	// Duty cycle = 39.63
		{ 0x33, 0x82 }, 	// Duty cycle = 39.69
		{ 0x64, 0xfd }, 	// Duty cycle = 39.76
		{ 0x5b, 0xe6 }, 	// Duty cycle = 39.83
		{ 0x4a, 0xbb }, 	// Duty cycle = 39.89
		{ 0x65, 0xfe }, 	// Duty cycle = 40.00
		{ 0x64, 0xfb }, 	// Duty cycle = 40.08
		{ 0x52, 0xce }, 	// Duty cycle = 40.10
		{ 0x61, 0xf3 }, 	// Duty cycle = 40.16
		{ 0x45, 0xad }, 	// Duty cycle = 40.23
		{ 0x50, 0xc8 }, 	// Duty cycle = 40.30
		{ 0x57, 0xd9 }, 	// Duty cycle = 40.37
		{ 0x5c, 0xe5 }, 	// Duty cycle = 40.43
		{ 0x50, 0xc7 }, 	// Duty cycle = 40.50
		{ 0x55, 0xd3 }, 	// Duty cycle = 40.57
		{ 0x65, 0xfa }, 	// Duty cycle = 40.64
		{ 0x50, 0xc6 }, 	// Duty cycle = 40.70
		{ 0x34, 0x81 }, 	// Duty cycle = 40.77
		{ 0x61, 0xef }, 	// Duty cycle = 40.83
		{ 0x62, 0xf1 }, 	// Duty cycle = 40.91
		{ 0x5c, 0xe2 }, 	// Duty cycle = 40.97
		{ 0x66, 0xfa }, 	// Duty cycle = 41.04
		{ 0x60, 0xeb }, 	// Duty cycle = 41.10
		{ 0x68, 0xfe }, 	// Duty cycle = 41.18
		{ 0x4f, 0xc1 }, 	// Duty cycle = 41.24
		{ 0x5e, 0xe5 }, 	// Duty cycle = 41.30
		{ 0x5f, 0xe7 }, 	// Duty cycle = 41.38
		{ 0x4a, 0xb4 }, 	// Duty cycle = 41.44
		{ 0x57, 0xd3 }, 	// Duty cycle = 41.51
		{ 0x49, 0xb1 }, 	// Duty cycle = 41.57
		{ 0x68, 0xfb }, 	// Duty cycle = 41.67
		{ 0x5c, 0xde }, 	// Duty cycle = 41.70
		{ 0x62, 0xec }, 	// Duty cycle = 41.77
		{ 0x63, 0xee }, 	// Duty cycle = 41.84
		{ 0x64, 0xf0 }, 	// Duty cycle = 41.91
		{ 0x65, 0xf2 }, 	// Duty cycle = 41.98
		{ 0x66, 0xf4 }, 	// Duty cycle = 42.04
		{ 0x6a, 0xfd }, 	// Duty cycle = 42.13
		{ 0x60, 0xe5 }, 	// Duty cycle = 42.17
		{ 0x61, 0xe7 }, 	// Duty cycle = 42.24
		{ 0x62, 0xe9 }, 	// Duty cycle = 42.31
		{ 0x58, 0xd1 }, 	// Duty cycle = 42.38
		{ 0x48, 0xab }, 	// Duty cycle = 42.44
		{ 0x68, 0xf6 }, 	// Duty cycle = 42.51
		{ 0x41, 0x9a }, 	// Duty cycle = 42.58
		{ 0x56, 0xcb }, 	// Duty cycle = 42.65
		{ 0x54, 0xc6 }, 	// Duty cycle = 42.71
		{ 0x4c, 0xb3 }, 	// Duty cycle = 42.78
		{ 0x6b, 0xfb }, 	// Duty cycle = 42.86
		{ 0x6c, 0xfd }, 	// Duty cycle = 42.91
		{ 0x64, 0xea }, 	// Duty cycle = 42.98
		{ 0x40, 0x96 }, 	// Duty cycle = 43.05
		{ 0x47, 0xa6 }, 	// Duty cycle = 43.11
		{ 0x5e, 0xdb }, 	// Duty cycle = 43.18
		{ 0x6c, 0xfb }, 	// Duty cycle = 43.25
		{ 0x50, 0xba }, 	// Duty cycle = 43.32
		{ 0x3a, 0x87 }, 	// Duty cycle = 43.38
		{ 0x3e, 0x90 }, 	// Duty cycle = 43.45
		{ 0x67, 0xee }, 	// Duty cycle = 43.51
		{ 0x65, 0xe9 }, 	// Duty cycle = 43.59
		{ 0x6d, 0xfb }, 	// Duty cycle = 43.65
		{ 0x4f, 0xb6 }, 	// Duty cycle = 43.72
		{ 0x50, 0xb8 }, 	// Duty cycle = 43.78
		{ 0x51, 0xba }, 	// Duty cycle = 43.85
		{ 0x40, 0x93 }, 	// Duty cycle = 43.92
		{ 0x6d, 0xf9 }, 	// Duty cycle = 44.00
		{ 0x63, 0xe2 }, 	// Duty cycle = 44.05
		{ 0x6c, 0xf6 }, 	// Duty cycle = 44.13
		{ 0x5e, 0xd6 }, 	// Duty cycle = 44.19
		{ 0x4c, 0xad }, 	// Duty cycle = 44.25
		{ 0x51, 0xb8 }, 	// Duty cycle = 44.32
		{ 0x56, 0xc3 }, 	// Duty cycle = 44.39
		{ 0x70, 0xfd }, 	// Duty cycle = 44.49
		{ 0x40, 0x91 }, 	// Duty cycle = 44.52
		{ 0x66, 0xe6 }, 	// Duty cycle = 44.59
		{ 0x5b, 0xcd }, 	// Duty cycle = 44.66
		{ 0x58, 0xc6 }, 	// Duty cycle = 44.72
		{ 0x55, 0xbf }, 	// Duty cycle = 44.79
		{ 0x6c, 0xf2 }, 	// Duty cycle = 44.86
		{ 0x5c, 0xce }, 	// Duty cycle = 44.93
		{ 0x6b, 0xef }, 	// Duty cycle = 45.00
		{ 0x71, 0xfc }, 	// Duty cycle = 45.06
		{ 0x57, 0xc2 }, 	// Duty cycle = 45.13
		{ 0x5d, 0xcf }, 	// Duty cycle = 45.19
		{ 0x68, 0xe7 }, 	// Duty cycle = 45.26
		{ 0x60, 0xd5 }, 	// Duty cycle = 45.33
		{ 0x44, 0x97 }, 	// Duty cycle = 45.39
		{ 0x73, 0xfe }, 	// Duty cycle = 45.49
		{ 0x6f, 0xf5 }, 	// Duty cycle = 45.53
		{ 0x57, 0xc0 }, 	// Duty cycle = 45.60
		{ 0x63, 0xda }, 	// Duty cycle = 45.66
		{ 0x5a, 0xc6 }, 	// Duty cycle = 45.73
		{ 0x6c, 0xed }, 	// Duty cycle = 45.80
		{ 0x3c, 0x84 }, 	// Duty cycle = 45.86
		{ 0x4e, 0xab }, 	// Duty cycle = 45.93
		{ 0x72, 0xf9 }, 	// Duty cycle = 46.00
		{ 0x74, 0xfd }, 	// Duty cycle = 46.06
		{ 0x71, 0xf6 }, 	// Duty cycle = 46.15
		{ 0x4e, 0xaa }, 	// Duty cycle = 46.20
		{ 0x5c, 0xc8 }, 	// Duty cycle = 46.27
		{ 0x71, 0xf5 }, 	// Duty cycle = 46.34
		{ 0x73, 0xf9 }, 	// Duty cycle = 46.40
		{ 0x4e, 0xa9 }, 	// Duty cycle = 46.47
		{ 0x5d, 0xc9 }, 	// Duty cycle = 46.53
		{ 0x5f, 0xcd }, 	// Duty cycle = 46.60
		{ 0x76, 0xfe }, 	// Duty cycle = 46.67
		{ 0x5c, 0xc6 }, 	// Duty cycle = 46.73
		{ 0x6d, 0xea }, 	// Duty cycle = 46.81
		{ 0x68, 0xdf }, 	// Duty cycle = 46.88
		{ 0x72, 0xf4 }, 	// Duty cycle = 46.94
		{ 0x65, 0xd8 }, 	// Duty cycle = 47.00
		{ 0x70, 0xef }, 	// Duty cycle = 47.08
		{ 0x6a, 0xe2 }, 	// Duty cycle = 47.14
		{ 0x4b, 0xa0 }, 	// Duty cycle = 47.20
		{ 0x67, 0xdb }, 	// Duty cycle = 47.27
		{ 0x4f, 0xa8 }, 	// Duty cycle = 47.34
		{ 0x3f, 0x86 }, 	// Duty cycle = 47.41
		{ 0x5d, 0xc5 }, 	// Duty cycle = 47.47
		{ 0x73, 0xf3 }, 	// Duty cycle = 47.54
		{ 0x77, 0xfb }, 	// Duty cycle = 47.62
		{ 0x51, 0xab }, 	// Duty cycle = 47.67
		{ 0x49, 0x9a }, 	// Duty cycle = 47.74
		{ 0x6c, 0xe3 }, 	// Duty cycle = 47.81
		{ 0x4e, 0xa4 }, 	// Duty cycle = 47.88
		{ 0x68, 0xda }, 	// Duty cycle = 47.95
		{ 0x78, 0xfb }, 	// Duty cycle = 48.02
		{ 0x63, 0xcf }, 	// Duty cycle = 48.08
		{ 0x74, 0xf2 }, 	// Duty cycle = 48.15
		{ 0x6b, 0xdf }, 	// Duty cycle = 48.21
		{ 0x6f, 0xe7 }, 	// Duty cycle = 48.28
		{ 0x48, 0x96 }, 	// Duty cycle = 48.34
		{ 0x79, 0xfb }, 	// Duty cycle = 48.41
		{ 0x6f, 0xe6 }, 	// Duty cycle = 48.48
		{ 0x74, 0xf0 }, 	// Duty cycle = 48.55
		{ 0x68, 0xd7 }, 	// Duty cycle = 48.61
		{ 0x6e, 0xe3 }, 	// Duty cycle = 48.68
		{ 0x74, 0xef }, 	// Duty cycle = 48.75
		{ 0x66, 0xd2 }, 	// Duty cycle = 48.82
		{ 0x6d, 0xe0 }, 	// Duty cycle = 48.89
		{ 0x5c, 0xbd }, 	// Duty cycle = 48.95
		{ 0x7c, 0xfe }, 	// Duty cycle = 49.02
		{ 0x6a, 0xd9 }, 	// Duty cycle = 49.08
		{ 0x73, 0xeb }, 	// Duty cycle = 49.15
		{ 0x5d, 0xbe }, 	// Duty cycle = 49.21
		{ 0x66, 0xd0 }, 	// Duty cycle = 49.28
		{ 0x71, 0xe6 }, 	// Duty cycle = 49.35
		{ 0x54, 0xab }, 	// Duty cycle = 49.42
		{ 0x5f, 0xc1 }, 	// Duty cycle = 49.48
		{ 0x6e, 0xdf }, 	// Duty cycle = 49.55
		{ 0x40, 0x82 }, 	// Duty cycle = 49.62
		{ 0x4e, 0x9e }, 	// Duty cycle = 49.69
		{ 0x63, 0xc8 }, 	// Duty cycle = 49.75
		{ 0x7e, 0xfd }, 	// Duty cycle = 50.00
		{ 0x7e, 0xfd }, 	// Duty cycle = 50.00
		{ 0x7e, 0xfd }, 	// Duty cycle = 50.00
		{ 0x7f, 0xfe }, 	// Duty cycle = 50.20
		{ 0x7f, 0xfe }, 	// Duty cycle = 50.20
		{ 0x7f, 0xfe }, 	// Duty cycle = 50.20
		{ 0x70, 0xe0 }, 	// Duty cycle = 50.22
		{ 0x56, 0xac }, 	// Duty cycle = 50.29
		{ 0x46, 0x8c }, 	// Duty cycle = 50.35
		{ 0x76, 0xeb }, 	// Duty cycle = 50.42
		{ 0x66, 0xcb }, 	// Duty cycle = 50.49
		{ 0x59, 0xb1 }, 	// Duty cycle = 50.56
		{ 0x50, 0x9f }, 	// Duty cycle = 50.62
		{ 0x6d, 0xd8 }, 	// Duty cycle = 50.69
		{ 0x42, 0x83 }, 	// Duty cycle = 50.76
		{ 0x7a, 0xf1 }, 	// Duty cycle = 50.83
		{ 0x71, 0xdf }, 	// Duty cycle = 50.89
		{ 0x69, 0xcf }, 	// Duty cycle = 50.96
		{ 0x7b, 0xf2 }, 	// Duty cycle = 51.03
		{ 0x45, 0x88 }, 	// Duty cycle = 51.09
		{ 0x6d, 0xd6 }, 	// Duty cycle = 51.16
		{ 0x7c, 0xf3 }, 	// Duty cycle = 51.23
		{ 0x62, 0xc0 }, 	// Duty cycle = 51.30
		{ 0x70, 0xdb }, 	// Duty cycle = 51.36
		{ 0x7d, 0xf4 }, 	// Duty cycle = 51.43
		{ 0x55, 0xa6 }, 	// Duty cycle = 51.50
		{ 0x62, 0xbf }, 	// Duty cycle = 51.56
		{ 0x5e, 0xb7 }, 	// Duty cycle = 51.63
		{ 0x4b, 0x92 }, 	// Duty cycle = 51.70
		{ 0x83, 0xfe }, 	// Duty cycle = 51.76
		{ 0x62, 0xbe }, 	// Duty cycle = 51.83
		{ 0x7a, 0xec }, 	// Duty cycle = 51.90
		{ 0x76, 0xe4 }, 	// Duty cycle = 51.97
		{ 0x7f, 0xf5 }, 	// Duty cycle = 52.03
		{ 0x7b, 0xed }, 	// Duty cycle = 52.10
		{ 0x83, 0xfc }, 	// Duty cycle = 52.17
		{ 0x74, 0xdf }, 	// Duty cycle = 52.23
		{ 0x7c, 0xee }, 	// Duty cycle = 52.30
		{ 0x83, 0xfb }, 	// Duty cycle = 52.38
		{ 0x80, 0xf5 }, 	// Duty cycle = 52.44
		{ 0x72, 0xda }, 	// Duty cycle = 52.51
		{ 0x84, 0xfc }, 	// Duty cycle = 52.57
		{ 0x80, 0xf4 }, 	// Duty cycle = 52.65
		{ 0x74, 0xdd }, 	// Duty cycle = 52.70
		{ 0x84, 0xfb }, 	// Duty cycle = 52.78
		{ 0x78, 0xe4 }, 	// Duty cycle = 52.84
		{ 0x51, 0x9a }, 	// Duty cycle = 52.90
		{ 0x6a, 0xc9 }, 	// Duty cycle = 52.97
		{ 0x5f, 0xb4 }, 	// Duty cycle = 53.04
		{ 0x5d, 0xb0 }, 	// Duty cycle = 53.11
		{ 0x85, 0xfb }, 	// Duty cycle = 53.17
		{ 0x72, 0xd7 }, 	// Duty cycle = 53.24
		{ 0x80, 0xf1 }, 	// Duty cycle = 53.31
		{ 0x56, 0xa2 }, 	// Duty cycle = 53.37
		{ 0x64, 0xbc }, 	// Duty cycle = 53.44
		{ 0x79, 0xe3 }, 	// Duty cycle = 53.51
		{ 0x7e, 0xec }, 	// Duty cycle = 53.59
		{ 0x50, 0x96 }, 	// Duty cycle = 53.64
		{ 0x7a, 0xe4 }, 	// Duty cycle = 53.71
		{ 0x78, 0xe0 }, 	// Duty cycle = 53.78
		{ 0x84, 0xf6 }, 	// Duty cycle = 53.85
		{ 0x82, 0xf2 }, 	// Duty cycle = 53.91
		{ 0x5e, 0xaf }, 	// Duty cycle = 53.98
		{ 0x77, 0xdd }, 	// Duty cycle = 54.05
		{ 0x7c, 0xe6 }, 	// Duty cycle = 54.11
		{ 0x87, 0xfa }, 	// Duty cycle = 54.18
		{ 0x72, 0xd3 }, 	// Duty cycle = 54.25
		{ 0x6a, 0xc4 }, 	// Duty cycle = 54.31
		{ 0x7b, 0xe3 }, 	// Duty cycle = 54.39
		{ 0x67, 0xbe }, 	// Duty cycle = 54.45
		{ 0x89, 0xfc }, 	// Duty cycle = 54.55
		{ 0x88, 0xfa }, 	// Duty cycle = 54.58
		{ 0x5d, 0xab }, 	// Duty cycle = 54.65
		{ 0x73, 0xd3 }, 	// Duty cycle = 54.72
		{ 0x7d, 0xe5 }, 	// Duty cycle = 54.78
		{ 0x81, 0xec }, 	// Duty cycle = 54.85
		{ 0x85, 0xf3 }, 	// Duty cycle = 54.92
		{ 0x83, 0xef }, 	// Duty cycle = 55.00
		{ 0x6c, 0xc5 }, 	// Duty cycle = 55.05
		{ 0x8b, 0xfd }, 	// Duty cycle = 55.12
		{ 0x84, 0xf0 }, 	// Duty cycle = 55.19
		{ 0x78, 0xda }, 	// Duty cycle = 55.25
		{ 0x81, 0xea }, 	// Duty cycle = 55.32
		{ 0x6b, 0xc2 }, 	// Duty cycle = 55.38
		{ 0x79, 0xdb }, 	// Duty cycle = 55.45
		{ 0x8b, 0xfb }, 	// Duty cycle = 55.56
		{ 0x8a, 0xf9 }, 	// Duty cycle = 55.60
		{ 0x7f, 0xe5 }, 	// Duty cycle = 55.65
		{ 0x6f, 0xc8 }, 	// Duty cycle = 55.72
		{ 0x69, 0xbd }, 	// Duty cycle = 55.79
		{ 0x7b, 0xdd }, 	// Duty cycle = 55.86
		{ 0x54, 0x97 }, 	// Duty cycle = 55.92
		{ 0x8b, 0xf9 }, 	// Duty cycle = 56.00
		{ 0x6e, 0xc5 }, 	// Duty cycle = 56.06
		{ 0x6d, 0xc3 }, 	// Duty cycle = 56.12
		{ 0x75, 0xd1 }, 	// Duty cycle = 56.19
		{ 0x8a, 0xf6 }, 	// Duty cycle = 56.28
		{ 0x89, 0xf4 }, 	// Duty cycle = 56.33
		{ 0x4a, 0x84 }, 	// Duty cycle = 56.39
		{ 0x75, 0xd0 }, 	// Duty cycle = 56.46
		{ 0x85, 0xec }, 	// Duty cycle = 56.54
		{ 0x66, 0xb5 }, 	// Duty cycle = 56.59
		{ 0x87, 0xef }, 	// Duty cycle = 56.67
		{ 0x60, 0xaa }, 	// Duty cycle = 56.73
		{ 0x74, 0xcd }, 	// Duty cycle = 56.80
		{ 0x90, 0xfe }, 	// Duty cycle = 56.86
		{ 0x72, 0xc9 }, 	// Duty cycle = 56.93
		{ 0x6d, 0xc0 }, 	// Duty cycle = 56.99
		{ 0x64, 0xb0 }, 	// Duty cycle = 57.06
		{ 0x8f, 0xfb }, 	// Duty cycle = 57.14
		{ 0x8e, 0xf9 }, 	// Duty cycle = 57.20
		{ 0x89, 0xf0 }, 	// Duty cycle = 57.26
		{ 0x80, 0xe0 }, 	// Duty cycle = 57.33
		{ 0x60, 0xa8 }, 	// Duty cycle = 57.40
		{ 0x4c, 0x85 }, 	// Duty cycle = 57.46
		{ 0x7d, 0xda }, 	// Duty cycle = 57.53
		{ 0x8f, 0xf9 }, 	// Duty cycle = 57.60
		{ 0x4e, 0x88 }, 	// Duty cycle = 57.66
		{ 0x6f, 0xc1 }, 	// Duty cycle = 57.73
		{ 0x7d, 0xd9 }, 	// Duty cycle = 57.80
		{ 0x66, 0xb1 }, 	// Duty cycle = 57.87
		{ 0x91, 0xfb }, 	// Duty cycle = 57.94
		{ 0x90, 0xf9 }, 	// Duty cycle = 58.00
		{ 0x84, 0xe4 }, 	// Duty cycle = 58.08
		{ 0x7c, 0xd6 }, 	// Duty cycle = 58.14
		{ 0x6d, 0xbc }, 	// Duty cycle = 58.20
		{ 0x93, 0xfd }, 	// Duty cycle = 58.27
		{ 0x8e, 0xf4 }, 	// Duty cycle = 58.37
		{ 0x8a, 0xed }, 	// Duty cycle = 58.40
		{ 0x6a, 0xb6 }, 	// Duty cycle = 58.47
		{ 0x8f, 0xf5 }, 	// Duty cycle = 58.54
		{ 0x7d, 0xd6 }, 	// Duty cycle = 58.60
		{ 0x72, 0xc3 }, 	// Duty cycle = 58.67
		{ 0x78, 0xcd }, 	// Duty cycle = 58.74
		{ 0x95, 0xfe }, 	// Duty cycle = 58.82
		{ 0x91, 0xf7 }, 	// Duty cycle = 58.87
		{ 0x58, 0x96 }, 	// Duty cycle = 58.94
		{ 0x5e, 0xa0 }, 	// Duty cycle = 59.01
		{ 0x8e, 0xf1 }, 	// Duty cycle = 59.09
		{ 0x6d, 0xb9 }, 	// Duty cycle = 59.14
		{ 0x86, 0xe3 }, 	// Duty cycle = 59.21
		{ 0x92, 0xf7 }, 	// Duty cycle = 59.27
		{ 0x6b, 0xb5 }, 	// Duty cycle = 59.34
		{ 0x64, 0xa9 }, 	// Duty cycle = 59.41
		{ 0x5a, 0x98 }, 	// Duty cycle = 59.48
		{ 0x4d, 0x82 }, 	// Duty cycle = 59.54
		{ 0x7b, 0xcf }, 	// Duty cycle = 59.62
		{ 0x93, 0xf7 }, 	// Duty cycle = 59.68
		{ 0x8c, 0xeb }, 	// Duty cycle = 59.75
		{ 0x7f, 0xd5 }, 	// Duty cycle = 59.81
		{ 0x63, 0xa6 }, 	// Duty cycle = 59.88
		{ 0x98, 0xfe }, 	// Duty cycle = 60.00
		{ 0x97, 0xfc }, 	// Duty cycle = 60.08
		{ 0x97, 0xfc }, 	// Duty cycle = 60.08
		{ 0x52, 0x89 }, 	// Duty cycle = 60.14
		{ 0x6f, 0xb9 }, 	// Duty cycle = 60.22
		{ 0x80, 0xd5 }, 	// Duty cycle = 60.28
		{ 0x88, 0xe2 }, 	// Duty cycle = 60.35
		{ 0x90, 0xef }, 	// Duty cycle = 60.42
		{ 0x95, 0xf7 }, 	// Duty cycle = 60.48
		{ 0x83, 0xd9 }, 	// Duty cycle = 60.55
		{ 0x88, 0xe1 }, 	// Duty cycle = 60.62
		{ 0x8d, 0xe9 }, 	// Duty cycle = 60.68
		{ 0x70, 0xb9 }, 	// Duty cycle = 60.75
		{ 0x94, 0xf4 }, 	// Duty cycle = 60.82
		{ 0x96, 0xf7 }, 	// Duty cycle = 60.89
		{ 0x7f, 0xd1 }, 	// Duty cycle = 60.95
		{ 0x8f, 0xeb }, 	// Duty cycle = 61.02
		{ 0x7b, 0xca }, 	// Duty cycle = 61.08
		{ 0x54, 0x8a }, 	// Duty cycle = 61.15
		{ 0x95, 0xf4 }, 	// Duty cycle = 61.22
		{ 0x97, 0xf7 }, 	// Duty cycle = 61.29
		{ 0x7e, 0xce }, 	// Duty cycle = 61.35
		{ 0x78, 0xc4 }, 	// Duty cycle = 61.42
		{ 0x5a, 0x93 }, 	// Duty cycle = 61.49
		{ 0x9c, 0xfe }, 	// Duty cycle = 61.57
		{ 0x71, 0xb8 }, 	// Duty cycle = 61.62
		{ 0x5e, 0x99 }, 	// Duty cycle = 61.69
		{ 0x92, 0xed }, 	// Duty cycle = 61.76
		{ 0x94, 0xf0 }, 	// Duty cycle = 61.83
		{ 0x9b, 0xfb }, 	// Duty cycle = 61.90
		{ 0x71, 0xb7 }, 	// Duty cycle = 61.96
		{ 0x92, 0xec }, 	// Duty cycle = 62.03
		{ 0x5e, 0x98 }, 	// Duty cycle = 62.09
		{ 0x89, 0xdd }, 	// Duty cycle = 62.16
		{ 0x90, 0xe8 }, 	// Duty cycle = 62.23
		{ 0x97, 0xf3 }, 	// Duty cycle = 62.30
		{ 0x6e, 0xb1 }, 	// Duty cycle = 62.36
		{ 0x6b, 0xac }, 	// Duty cycle = 62.43
		{ 0x9a, 0xf7 }, 	// Duty cycle = 62.50
		{ 0x83, 0xd2 }, 	// Duty cycle = 62.56
		{ 0x7b, 0xc5 }, 	// Duty cycle = 62.63
		{ 0x78, 0xc0 }, 	// Duty cycle = 62.69
		{ 0x95, 0xee }, 	// Duty cycle = 62.76
		{ 0x77, 0xbe }, 	// Duty cycle = 62.83
		{ 0x8a, 0xdc }, 	// Duty cycle = 62.90
		{ 0x98, 0xf2 }, 	// Duty cycle = 62.96
		{ 0x67, 0xa4 }, 	// Duty cycle = 63.03
		{ 0x75, 0xba }, 	// Duty cycle = 63.10
		{ 0x96, 0xee }, 	// Duty cycle = 63.18
		{ 0x80, 0xcb }, 	// Duty cycle = 63.24
		{ 0x76, 0xbb }, 	// Duty cycle = 63.30
		{ 0x7f, 0xc9 }, 	// Duty cycle = 63.37
		{ 0x54, 0x85 }, 	// Duty cycle = 63.43
		{ 0x7e, 0xc7 }, 	// Duty cycle = 63.50
		{ 0x51, 0x80 }, 	// Duty cycle = 63.57
		{ 0xa0, 0xfc }, 	// Duty cycle = 63.64
		{ 0x55, 0x86 }, 	// Duty cycle = 63.70
		{ 0x83, 0xce }, 	// Duty cycle = 63.77
		{ 0x8e, 0xdf }, 	// Duty cycle = 63.84
		{ 0x99, 0xf0 }, 	// Duty cycle = 63.90
		{ 0x9d, 0xf6 }, 	// Duty cycle = 63.97
		{ 0x91, 0xe3 }, 	// Duty cycle = 64.04
		{ 0x95, 0xe9 }, 	// Duty cycle = 64.10
		{ 0x77, 0xba }, 	// Duty cycle = 64.17
		{ 0x60, 0x96 }, 	// Duty cycle = 64.24
		{ 0xa3, 0xfe }, 	// Duty cycle = 64.31
		{ 0x9e, 0xf6 }, 	// Duty cycle = 64.37
		{ 0x90, 0xe0 }, 	// Duty cycle = 64.44
		{ 0x9f, 0xf7 }, 	// Duty cycle = 64.52
		{ 0x70, 0xae }, 	// Duty cycle = 64.57
		{ 0x74, 0xb4 }, 	// Duty cycle = 64.64
		{ 0xa4, 0xfe }, 	// Duty cycle = 64.71
		{ 0x71, 0xaf }, 	// Duty cycle = 64.77
		{ 0x8d, 0xda }, 	// Duty cycle = 64.84
		{ 0x93, 0xe3 }, 	// Duty cycle = 64.91
		{ 0x7f, 0xc4 }, 	// Duty cycle = 64.97
		{ 0x9f, 0xf5 } 	// Duty cycle = 65.04
};

const uint8_t NTC_LOOKUP[33] PROGMEM = {
		0x00, 	// ADC=0, Temperature=0
		0x04, 	// ADC=32, Temperature=4
		0x13, 	// ADC=64, Temperature=19
		0x1d, 	// ADC=96, Temperature=29
		0x24, 	// ADC=128, Temperature=36
		0x2b, 	// ADC=160, Temperature=43
		0x31, 	// ADC=192, Temperature=49
		0x36, 	// ADC=224, Temperature=54
		0x3b, 	// ADC=256, Temperature=59
		0x3f, 	// ADC=288, Temperature=63
		0x43, 	// ADC=320, Temperature=67
		0x48, 	// ADC=352, Temperature=72
		0x4c, 	// ADC=384, Temperature=76
		0x50, 	// ADC=416, Temperature=80
		0x54, 	// ADC=448, Temperature=84
		0x58, 	// ADC=480, Temperature=88
		0x5c, 	// ADC=512, Temperature=92
		0x60, 	// ADC=544, Temperature=96
		0x64, 	// ADC=576, Temperature=100
		0x68, 	// ADC=608, Temperature=104
		0x6d, 	// ADC=640, Temperature=109
		0x72, 	// ADC=672, Temperature=114
		0x77, 	// ADC=704, Temperature=119
		0x7c, 	// ADC=736, Temperature=124
		0x82, 	// ADC=768, Temperature=130
		0x88, 	// ADC=800, Temperature=136
		0x8f, 	// ADC=832, Temperature=143
		0x97, 	// ADC=864, Temperature=151
		0xa0, 	// ADC=896, Temperature=160
		0xab, 	// ADC=928, Temperature=171
		0xb9, 	// ADC=960, Temperature=185
		0xcc, 	// ADC=992, Temperature=204
		0xe9 	// ADC=1024, Temperature=233
};

void boost_Init() {
	/* setup PWM on OC0B (PA7) */
	/* initially set pin low -> FET is off */
	PORTA &= ~(1 << PA7);
	DDRA |= (1 << PA7);

	/* initialize default voltage/current limits */
	boost_setCurrent(0);
	boost_setMaxVoltage(37000);
	boost_setMaxTemperature(BOOST_MAX_TEMP);

	boost.isEnabled = 0;
	boost.active = 0;

	/* set callback to update boost converter */
//	adc_setCallback(boost_Update);
}

void boost_Enable() {
	/* initialize PWM value, start with lowest PWM value */
	boost.dutyCycleIt = 0;
	boost_updatePWM();
	/* set non-inverting fast PWM mode, using OCR0A as TOP */
	TCCR0A |= (1 << COM0B1) | (1 << WGM01) | (1 << WGM00);
	/* set PWM as fast as possible, results in 78kHz PWM frequency */
	TCCR0B |= (1 << CS00) | (1 << WGM02);
	boost.isEnabled = 1;
}

void boost_Disable() {
	/* set pin low -> FET is off (should already be low, just a safety measure) */
	PORTA &= ~(1 << PA7);
	DDRA |= (1 << PA7);
	/* disable PWM */
	TCCR0A = TCCR0B = 0;
	boost.isEnabled = 0;
}

void boost_Update(void) {
	/* calculate values from raw ADC data */
	boost.current = (adc.raw[ADC_CURRENT] * 100000UL)
			/ (93UL * BOOST_SHUNT_VALUE);
	boost.voltage = (adc.raw[ADC_VOLTAGE] * 100UL * BOOST_VOL_SENS_FACT) / 93;

	/* interpolate temperature from lookup-table */
	uint8_t index = adc.raw[ADC_TEMPERATURE] / 32;
	uint8_t interpolate = adc.raw[ADC_TEMPERATURE] % 32;
	boost.temperature = pgm_read_byte(&NTC_LOOKUP[index]);
	boost.temperature += (pgm_read_byte(&NTC_LOOKUP[index + 1])
			- boost.temperature) * interpolate / 32;

	if (!boost.isEnabled && boost.active
			&& (boost.maxTemp >= boost.temperature)) {
		/* was disabled, now active and temperature is OK */
		boost_Enable();
	} else if (boost.isEnabled
			&& (!boost.active || (boost.maxTemp < boost.temperature))) {
		/* was active, now disabled or temperature too hot */
		boost_Disable();
	}
	if (boost.isEnabled) {
		if (boost.voltage > boost.setVoltage) {
			/* voltage at limit -> decrease duty cycle */
			boost.dutyCycleIt--;
		} else {
			/* voltage not at limit -> control current */
			int16_t currDiff = boost.setCurrent - boost.current;
			/* change duty cycle */
			int16_t change = currDiff / 5;
			if (change > 10) {
				change = 10;
			} else if (change < -10) {
				change = -10;
			}
			boost.dutyCycleIt += change;
		}
		if (boost.dutyCycleIt < 0)
			boost.dutyCycleIt = 0;
		else if (boost.dutyCycleIt > (int16_t) (sizeof(PWM_LOOKUP) / 2 - 1))
			boost.dutyCycleIt = sizeof(PWM_LOOKUP) / 2 - 1;
		boost_updatePWM();
	}
}

void boost_setCurrent(uint16_t mA) {
	if (mA > BOOST_MAX_CURRENT)
		/* limit current to maximum */
		mA = BOOST_MAX_CURRENT;
	boost.setCurrent = mA;
}

void boost_setMaxVoltage(uint16_t mV) {
	if (mV > BOOST_MAX_VOLTAGE)
		/* limit voltage to maximum */
		mV = BOOST_MAX_VOLTAGE;
	boost.setVoltage = mV;
}

void boost_setMaxTemperature(uint8_t deg) {
	boost.maxTemp = deg;
}

void boost_updatePWM(void) {
	/* extract PWM generation values and store in registers */
	OCR0B = pgm_read_byte(&PWM_LOOKUP[boost.dutyCycleIt][0]);
	OCR0A = pgm_read_byte(&PWM_LOOKUP[boost.dutyCycleIt][1]);
}
