/**
 * \file
 * \brief Boost converter regulation and safety functions
 */
#include "boost.h"

/**
 * Duty cycle lookup-table. Generated by Python-script.
 */
const uint8_t PWM_LOOKUP[][2] PROGMEM = {
	{0x01, 0xc7}, 	// Duty cycle = 1.00
	{0x01, 0xb6}, 	// Duty cycle = 1.09
	{0x02, 0xfd}, 	// Duty cycle = 1.18
	{0x02, 0xeb}, 	// Duty cycle = 1.27
	{0x01, 0x92}, 	// Duty cycle = 1.36
	{0x02, 0xce}, 	// Duty cycle = 1.45
	{0x02, 0xc2}, 	// Duty cycle = 1.54
	{0x02, 0xb7}, 	// Duty cycle = 1.63
	{0x03, 0xe8}, 	// Duty cycle = 1.72
	{0x02, 0xa5}, 	// Duty cycle = 1.81
	{0x03, 0xd2}, 	// Duty cycle = 1.90
	{0x04, 0xfb}, 	// Duty cycle = 1.98
	{0x04, 0xf0}, 	// Duty cycle = 2.07
	{0x04, 0xe6}, 	// Duty cycle = 2.16
	{0x04, 0xdd}, 	// Duty cycle = 2.25
	{0x02, 0x7f}, 	// Duty cycle = 2.34
	{0x05, 0xf5}, 	// Duty cycle = 2.44
	{0x05, 0xed}, 	// Duty cycle = 2.52
	{0x03, 0x98}, 	// Duty cycle = 2.61
	{0x05, 0xdd}, 	// Duty cycle = 2.70
	{0x06, 0xfa}, 	// Duty cycle = 2.79
	{0x06, 0xf2}, 	// Duty cycle = 2.88
	{0x05, 0xc9}, 	// Duty cycle = 2.97
	{0x05, 0xc3}, 	// Duty cycle = 3.06
	{0x07, 0xfd}, 	// Duty cycle = 3.15
	{0x07, 0xf6}, 	// Duty cycle = 3.24
	{0x07, 0xef}, 	// Duty cycle = 3.33
	{0x07, 0xe9}, 	// Duty cycle = 3.42
	{0x07, 0xe3}, 	// Duty cycle = 3.51
	{0x04, 0x8a}, 	// Duty cycle = 3.60
	{0x06, 0xbd}, 	// Duty cycle = 3.68
	{0x07, 0xd3}, 	// Duty cycle = 3.77
	{0x08, 0xe8}, 	// Duty cycle = 3.86
	{0x09, 0xfc}, 	// Duty cycle = 3.95
	{0x06, 0xac}, 	// Duty cycle = 4.05
	{0x09, 0xf1}, 	// Duty cycle = 4.13
	{0x08, 0xd4}, 	// Duty cycle = 4.23
	{0x09, 0xe7}, 	// Duty cycle = 4.31
	{0x0a, 0xf9}, 	// Duty cycle = 4.40
	{0x0a, 0xf4}, 	// Duty cycle = 4.49
	{0x05, 0x82}, 	// Duty cycle = 4.58
	{0x09, 0xd5}, 	// Duty cycle = 4.67
	{0x0b, 0xfb}, 	// Duty cycle = 4.76
	{0x07, 0xa4}, 	// Duty cycle = 4.85
	{0x0b, 0xf2}, 	// Duty cycle = 4.94
	{0x09, 0xc6}, 	// Duty cycle = 5.03
	{0x0a, 0xd6}, 	// Duty cycle = 5.12
	{0x09, 0xbf}, 	// Duty cycle = 5.21
	{0x08, 0xa9}, 	// Duty cycle = 5.29
	{0x06, 0x81}, 	// Duty cycle = 5.38
	{0x0a, 0xc8}, 	// Duty cycle = 5.47
	{0x0d, 0xfa}, 	// Duty cycle = 5.58
	{0x0c, 0xe5}, 	// Duty cycle = 5.65
	{0x0b, 0xd0}, 	// Duty cycle = 5.74
	{0x0d, 0xef}, 	// Duty cycle = 5.83
	{0x08, 0x97}, 	// Duty cycle = 5.92
	{0x0a, 0xb6}, 	// Duty cycle = 6.01
	{0x0c, 0xd4}, 	// Duty cycle = 6.10
	{0x0c, 0xd1}, 	// Duty cycle = 6.19
	{0x0d, 0xde}, 	// Duty cycle = 6.28
	{0x09, 0x9c}, 	// Duty cycle = 6.37
	{0x0e, 0xe7}, 	// Duty cycle = 6.47
	{0x0a, 0xa7}, 	// Duty cycle = 6.55
	{0x0d, 0xd2}, 	// Duty cycle = 6.64
	{0x0e, 0xde}, 	// Duty cycle = 6.73
	{0x0e, 0xdb}, 	// Duty cycle = 6.82
	{0x10, 0xf5}, 	// Duty cycle = 6.91
	{0x09, 0x8e}, 	// Duty cycle = 6.99
	{0x10, 0xef}, 	// Duty cycle = 7.08
	{0x10, 0xec}, 	// Duty cycle = 7.17
	{0x0c, 0xb2}, 	// Duty cycle = 7.26
	{0x0e, 0xcb}, 	// Duty cycle = 7.35
	{0x0f, 0xd6}, 	// Duty cycle = 7.44
	{0x11, 0xee}, 	// Duty cycle = 7.53
	{0x0f, 0xd1}, 	// Duty cycle = 7.62
	{0x12, 0xf5}, 	// Duty cycle = 7.72
	{0x10, 0xd9}, 	// Duty cycle = 7.80
	{0x11, 0xe3}, 	// Duty cycle = 7.89
	{0x0e, 0xbb}, 	// Duty cycle = 7.98
	{0x11, 0xde}, 	// Duty cycle = 8.07
	{0x13, 0xf4}, 	// Duty cycle = 8.16
	{0x0f, 0xc1}, 	// Duty cycle = 8.25
	{0x14, 0xfa}, 	// Duty cycle = 8.37
	{0x0e, 0xb1}, 	// Duty cycle = 8.43
	{0x12, 0xde}, 	// Duty cycle = 8.52
	{0x14, 0xf3}, 	// Duty cycle = 8.61
	{0x15, 0xfc}, 	// Duty cycle = 8.70
	{0x0c, 0x93}, 	// Duty cycle = 8.78
	{0x15, 0xf7}, 	// Duty cycle = 8.87
	{0x12, 0xd3}, 	// Duty cycle = 8.96
	{0x13, 0xdc}, 	// Duty cycle = 9.05
	{0x10, 0xb9}, 	// Duty cycle = 9.14
	{0x11, 0xc2}, 	// Duty cycle = 9.23
	{0x15, 0xeb}, 	// Duty cycle = 9.32
	{0x17, 0xfe}, 	// Duty cycle = 9.41
	{0x10, 0xb2}, 	// Duty cycle = 9.50
	{0x14, 0xda}, 	// Duty cycle = 9.59
	{0x17, 0xf7}, 	// Duty cycle = 9.68
	{0x14, 0xd6}, 	// Duty cycle = 9.77
	{0x14, 0xd4}, 	// Duty cycle = 9.86
	{0x11, 0xb4}, 	// Duty cycle = 9.94
	{0x18, 0xf8}, 	// Duty cycle = 10.04
	{0x17, 0xec}, 	// Duty cycle = 10.13
	{0x17, 0xea}, 	// Duty cycle = 10.21
	{0x10, 0xa4}, 	// Duty cycle = 10.30
	{0x14, 0xc9}, 	// Duty cycle = 10.40
	{0x19, 0xf7}, 	// Duty cycle = 10.48
	{0x17, 0xe2}, 	// Duty cycle = 10.57
	{0x14, 0xc4}, 	// Duty cycle = 10.66
	{0x13, 0xb9}, 	// Duty cycle = 10.75
	{0x1a, 0xf8}, 	// Duty cycle = 10.84
	{0x13, 0xb6}, 	// Duty cycle = 10.93
	{0x1a, 0xf4}, 	// Duty cycle = 11.02
	{0x1b, 0xfb}, 	// Duty cycle = 11.11
	{0x1b, 0xf9}, 	// Duty cycle = 11.20
	{0x1b, 0xf7}, 	// Duty cycle = 11.29
	{0x12, 0xa6}, 	// Duty cycle = 11.38
	{0x11, 0x9c}, 	// Duty cycle = 11.46
	{0x19, 0xe0}, 	// Duty cycle = 11.56
	{0x10, 0x91}, 	// Duty cycle = 11.64
	{0x16, 0xc3}, 	// Duty cycle = 11.73
	{0x17, 0xca}, 	// Duty cycle = 11.82
	{0x1b, 0xea}, 	// Duty cycle = 11.91
	{0x1b, 0xe8}, 	// Duty cycle = 12.02
	{0x19, 0xd6}, 	// Duty cycle = 12.09
	{0x17, 0xc4}, 	// Duty cycle = 12.18
	{0x13, 0xa2}, 	// Duty cycle = 12.27
	{0x15, 0xb1}, 	// Duty cycle = 12.36
	{0x1e, 0xf8}, 	// Duty cycle = 12.45
	{0x1f, 0xfe}, 	// Duty cycle = 12.55
	{0x17, 0xbd}, 	// Duty cycle = 12.63
	{0x15, 0xac}, 	// Duty cycle = 12.72
	{0x19, 0xca}, 	// Duty cycle = 12.81
	{0x1f, 0xf7}, 	// Duty cycle = 12.90
	{0x1d, 0xe6}, 	// Duty cycle = 12.99
	{0x10, 0x81}, 	// Duty cycle = 13.08
	{0x1f, 0xf2}, 	// Duty cycle = 13.17
	{0x17, 0xb4}, 	// Duty cycle = 13.26
	{0x20, 0xf6}, 	// Duty cycle = 13.36
	{0x1a, 0xc8}, 	// Duty cycle = 13.43
	{0x20, 0xf3}, 	// Duty cycle = 13.52
	{0x19, 0xbe}, 	// Duty cycle = 13.61
	{0x1a, 0xc4}, 	// Duty cycle = 13.71
	{0x1f, 0xe7}, 	// Duty cycle = 13.79
	{0x22, 0xfb}, 	// Duty cycle = 13.89
	{0x12, 0x87}, 	// Duty cycle = 13.97
	{0x1a, 0xbf}, 	// Duty cycle = 14.06
	{0x1d, 0xd3}, 	// Duty cycle = 14.15
	{0x23, 0xfb}, 	// Duty cycle = 14.29
	{0x23, 0xfa}, 	// Duty cycle = 14.34
	{0x1e, 0xd6}, 	// Duty cycle = 14.42
	{0x1b, 0xc0}, 	// Duty cycle = 14.51
	{0x13, 0x88}, 	// Duty cycle = 14.60
	{0x14, 0x8e}, 	// Duty cycle = 14.69
	{0x1d, 0xca}, 	// Duty cycle = 14.78
	{0x20, 0xdd}, 	// Duty cycle = 14.86
	{0x1f, 0xd5}, 	// Duty cycle = 14.95
	{0x21, 0xe1}, 	// Duty cycle = 15.04
	{0x16, 0x97}, 	// Duty cycle = 15.13
	{0x24, 0xf2}, 	// Duty cycle = 15.23
	{0x1f, 0xd0}, 	// Duty cycle = 15.31
	{0x26, 0xfc}, 	// Duty cycle = 15.42
	{0x20, 0xd4}, 	// Duty cycle = 15.49
	{0x23, 0xe6}, 	// Duty cycle = 15.58
	{0x21, 0xd8}, 	// Duty cycle = 15.67
	{0x19, 0xa4}, 	// Duty cycle = 15.76
	{0x1c, 0xb6}, 	// Duty cycle = 15.85
	{0x20, 0xce}, 	// Duty cycle = 15.94
	{0x14, 0x82}, 	// Duty cycle = 16.03
	{0x26, 0xf1}, 	// Duty cycle = 16.12
	{0x28, 0xfc}, 	// Duty cycle = 16.21
	{0x15, 0x86}, 	// Duty cycle = 16.30
	{0x1c, 0xb0}, 	// Duty cycle = 16.38
	{0x1c, 0xaf}, 	// Duty cycle = 16.48
	{0x1a, 0xa2}, 	// Duty cycle = 16.56
	{0x29, 0xfb}, 	// Duty cycle = 16.67
	{0x24, 0xdc}, 	// Duty cycle = 16.74
	{0x21, 0xc9}, 	// Duty cycle = 16.83
	{0x20, 0xc2}, 	// Duty cycle = 16.92
	{0x20, 0xc1}, 	// Duty cycle = 17.01
	{0x26, 0xe3}, 	// Duty cycle = 17.11
	{0x25, 0xdc}, 	// Duty cycle = 17.19
	{0x29, 0xf2}, 	// Duty cycle = 17.28
	{0x20, 0xbd}, 	// Duty cycle = 17.37
	{0x2b, 0xfb}, 	// Duty cycle = 17.46
	{0x2a, 0xf4}, 	// Duty cycle = 17.55
	{0x2c, 0xfe}, 	// Duty cycle = 17.65
	{0x26, 0xdb}, 	// Duty cycle = 17.73
	{0x1e, 0xad}, 	// Duty cycle = 17.82
	{0x23, 0xc8}, 	// Duty cycle = 17.91
	{0x2c, 0xf9}, 	// Duty cycle = 18.00
	{0x21, 0xbb}, 	// Duty cycle = 18.09
	{0x2d, 0xfc}, 	// Duty cycle = 18.18
	{0x27, 0xda}, 	// Duty cycle = 18.26
	{0x1c, 0x9d}, 	// Duty cycle = 18.35
	{0x2c, 0xf3}, 	// Duty cycle = 18.44
	{0x2a, 0xe7}, 	// Duty cycle = 18.53
	{0x1a, 0x90}, 	// Duty cycle = 18.62
	{0x1c, 0x9a}, 	// Duty cycle = 18.71
	{0x2e, 0xf9}, 	// Duty cycle = 18.80
	{0x21, 0xb3}, 	// Duty cycle = 18.89
	{0x19, 0x88}, 	// Duty cycle = 18.98
	{0x2c, 0xeb}, 	// Duty cycle = 19.07
	{0x28, 0xd5}, 	// Duty cycle = 19.16
	{0x2d, 0xee}, 	// Duty cycle = 19.25
	{0x22, 0xb4}, 	// Duty cycle = 19.34
	{0x21, 0xae}, 	// Duty cycle = 19.43
	{0x30, 0xfa}, 	// Duty cycle = 19.52
	{0x31, 0xfe}, 	// Duty cycle = 19.61
	{0x26, 0xc5}, 	// Duty cycle = 19.70
	{0x24, 0xba}, 	// Duty cycle = 19.79
	{0x1e, 0x9b}, 	// Duty cycle = 19.87
	{0x32, 0xfe}, 	// Duty cycle = 20.00
	{0x32, 0xfd}, 	// Duty cycle = 20.08
	{0x1b, 0x8a}, 	// Duty cycle = 20.14
	{0x22, 0xac}, 	// Duty cycle = 20.23
	{0x25, 0xba}, 	// Duty cycle = 20.32
	{0x30, 0xef}, 	// Duty cycle = 20.42
	{0x28, 0xc7}, 	// Duty cycle = 20.50
	{0x30, 0xed}, 	// Duty cycle = 20.59
	{0x2f, 0xe7}, 	// Duty cycle = 20.69
	{0x1a, 0x81}, 	// Duty cycle = 20.77
	{0x26, 0xba}, 	// Duty cycle = 20.86
	{0x1e, 0x93}, 	// Duty cycle = 20.95
	{0x33, 0xf6}, 	// Duty cycle = 21.05
	{0x2c, 0xd4}, 	// Duty cycle = 21.13
	{0x33, 0xf4}, 	// Duty cycle = 21.22
	{0x30, 0xe5}, 	// Duty cycle = 21.30
	{0x2a, 0xc8}, 	// Duty cycle = 21.39
	{0x33, 0xf1}, 	// Duty cycle = 21.49
	{0x33, 0xf0}, 	// Duty cycle = 21.58
	{0x33, 0xef}, 	// Duty cycle = 21.67
	{0x33, 0xee}, 	// Duty cycle = 21.76
	{0x2c, 0xcd}, 	// Duty cycle = 21.84
	{0x31, 0xe3}, 	// Duty cycle = 21.93
	{0x2f, 0xd9}, 	// Duty cycle = 22.02
	{0x2b, 0xc6}, 	// Duty cycle = 22.11
	{0x37, 0xfb}, 	// Duty cycle = 22.22
	{0x24, 0xa5}, 	// Duty cycle = 22.29
	{0x1f, 0x8e}, 	// Duty cycle = 22.38
	{0x32, 0xe2}, 	// Duty cycle = 22.47
	{0x1d, 0x84}, 	// Duty cycle = 22.56
	{0x34, 0xe9}, 	// Duty cycle = 22.65
	{0x39, 0xfe}, 	// Duty cycle = 22.75
	{0x29, 0xb7}, 	// Duty cycle = 22.83
	{0x36, 0xef}, 	// Duty cycle = 22.92
	{0x30, 0xd4}, 	// Duty cycle = 23.00
	{0x39, 0xfa}, 	// Duty cycle = 23.11
	{0x32, 0xdb}, 	// Duty cycle = 23.18
	{0x24, 0x9e}, 	// Duty cycle = 23.27
	{0x38, 0xf3}, 	// Duty cycle = 23.36
	{0x34, 0xe1}, 	// Duty cycle = 23.45
	{0x38, 0xf1}, 	// Duty cycle = 23.55
	{0x37, 0xec}, 	// Duty cycle = 23.63
	{0x24, 0x9b}, 	// Duty cycle = 23.72
	{0x3b, 0xfb}, 	// Duty cycle = 23.81
	{0x25, 0x9e}, 	// Duty cycle = 23.90
	{0x3b, 0xf9}, 	// Duty cycle = 24.00
	{0x3a, 0xf4}, 	// Duty cycle = 24.08
	{0x39, 0xef}, 	// Duty cycle = 24.17
	{0x38, 0xea}, 	// Duty cycle = 24.26
	{0x37, 0xe5}, 	// Duty cycle = 24.35
	{0x35, 0xdc}, 	// Duty cycle = 24.43
	{0x33, 0xd3}, 	// Duty cycle = 24.53
	{0x2f, 0xc2}, 	// Duty cycle = 24.62
	{0x3e, 0xfe}, 	// Duty cycle = 24.71
	{0x3b, 0xf1}, 	// Duty cycle = 24.79
	{0x33, 0xd0}, 	// Duty cycle = 24.88
	{0x3e, 0xfb}, 	// Duty cycle = 25.00
	{0x3f, 0xfe}, 	// Duty cycle = 25.10
	{0x29, 0xa6}, 	// Duty cycle = 25.15
	{0x34, 0xd1}, 	// Duty cycle = 25.24
	{0x39, 0xe4}, 	// Duty cycle = 25.33
	{0x3b, 0xeb}, 	// Duty cycle = 25.42
	{0x31, 0xc3}, 	// Duty cycle = 25.51
	{0x3f, 0xf9}, 	// Duty cycle = 25.60
	{0x37, 0xd9}, 	// Duty cycle = 25.69
	{0x39, 0xe0}, 	// Duty cycle = 25.78
	{0x33, 0xc8}, 	// Duty cycle = 25.87
	{0x21, 0x82}, 	// Duty cycle = 25.95
	{0x37, 0xd6}, 	// Duty cycle = 26.05
	{0x2d, 0xaf}, 	// Duty cycle = 26.14
	{0x3a, 0xe0}, 	// Duty cycle = 26.22
	{0x40, 0xf6}, 	// Duty cycle = 26.32
	{0x2e, 0xb1}, 	// Duty cycle = 26.40
	{0x3d, 0xe9}, 	// Duty cycle = 26.50
	{0x3e, 0xec}, 	// Duty cycle = 26.58
	{0x42, 0xfa}, 	// Duty cycle = 26.69
	{0x38, 0xd4}, 	// Duty cycle = 26.76
	{0x39, 0xd7}, 	// Duty cycle = 26.85
	{0x41, 0xf4}, 	// Duty cycle = 26.94
	{0x3b, 0xdd}, 	// Duty cycle = 27.03
	{0x3f, 0xeb}, 	// Duty cycle = 27.12
	{0x24, 0x87}, 	// Duty cycle = 27.21
	{0x43, 0xf8}, 	// Duty cycle = 27.31
	{0x41, 0xf0}, 	// Duty cycle = 27.39
	{0x3c, 0xdd}, 	// Duty cycle = 27.48
	{0x2a, 0x9b}, 	// Duty cycle = 27.56
	{0x40, 0xea}, 	// Duty cycle = 27.66
	{0x2f, 0xac}, 	// Duty cycle = 27.75
	{0x35, 0xc1}, 	// Duty cycle = 27.84
	{0x2a, 0x99}, 	// Duty cycle = 27.92
	{0x40, 0xe7}, 	// Duty cycle = 28.02
	{0x2a, 0x98}, 	// Duty cycle = 28.10
	{0x34, 0xbb}, 	// Duty cycle = 28.19
	{0x37, 0xc5}, 	// Duty cycle = 28.28
	{0x27, 0x8c}, 	// Duty cycle = 28.37
	{0x47, 0xfc}, 	// Duty cycle = 28.46
	{0x47, 0xfb}, 	// Duty cycle = 28.57
	{0x3c, 0xd4}, 	// Duty cycle = 28.64
	{0x33, 0xb4}, 	// Duty cycle = 28.73
	{0x41, 0xe4}, 	// Duty cycle = 28.82
	{0x24, 0x7f}, 	// Duty cycle = 28.91
	{0x39, 0xc7}, 	// Duty cycle = 29.00
	{0x3f, 0xdb}, 	// Duty cycle = 29.09
	{0x43, 0xe8}, 	// Duty cycle = 29.18
	{0x47, 0xf5}, 	// Duty cycle = 29.27
	{0x3a, 0xc8}, 	// Duty cycle = 29.35
	{0x34, 0xb3}, 	// Duty cycle = 29.44
	{0x38, 0xc0}, 	// Duty cycle = 29.53
	{0x47, 0xf2}, 	// Duty cycle = 29.63
	{0x28, 0x89}, 	// Duty cycle = 29.71
	{0x2c, 0x96}, 	// Duty cycle = 29.80
	{0x36, 0xb7}, 	// Duty cycle = 29.89
	{0x4a, 0xf9}, 	// Duty cycle = 30.00
	{0x2a, 0x8e}, 	// Duty cycle = 30.07
	{0x4b, 0xfb}, 	// Duty cycle = 30.16
	{0x30, 0xa1}, 	// Duty cycle = 30.25
	{0x35, 0xb1}, 	// Duty cycle = 30.34
	{0x4c, 0xfc}, 	// Duty cycle = 30.43
	{0x40, 0xd4}, 	// Duty cycle = 30.52
	{0x4a, 0xf4}, 	// Duty cycle = 30.61
	{0x41, 0xd6}, 	// Duty cycle = 30.70
	{0x4c, 0xf9}, 	// Duty cycle = 30.80
	{0x42, 0xd8}, 	// Duty cycle = 30.88
	{0x49, 0xee}, 	// Duty cycle = 30.96
	{0x3a, 0xbd}, 	// Duty cycle = 31.05
	{0x4b, 0xf3}, 	// Duty cycle = 31.15
	{0x4a, 0xef}, 	// Duty cycle = 31.25
	{0x4d, 0xf8}, 	// Duty cycle = 31.33
	{0x30, 0x9b}, 	// Duty cycle = 31.41
	{0x3e, 0xc7}, 	// Duty cycle = 31.50
	{0x4e, 0xf9}, 	// Duty cycle = 31.60
	{0x3f, 0xc9}, 	// Duty cycle = 31.68
	{0x3c, 0xbf}, 	// Duty cycle = 31.77
	{0x47, 0xe1}, 	// Duty cycle = 31.86
	{0x4c, 0xf0}, 	// Duty cycle = 31.95
	{0x41, 0xcd}, 	// Duty cycle = 32.04
	{0x46, 0xdc}, 	// Duty cycle = 32.13
	{0x2f, 0x94}, 	// Duty cycle = 32.21
	{0x3e, 0xc2}, 	// Duty cycle = 32.31
	{0x44, 0xd4}, 	// Duty cycle = 32.39
	{0x32, 0x9c}, 	// Duty cycle = 32.48
	{0x2a, 0x83}, 	// Duty cycle = 32.58
	{0x40, 0xc6}, 	// Duty cycle = 32.66
	{0x4a, 0xe4}, 	// Duty cycle = 32.75
	{0x42, 0xcb}, 	// Duty cycle = 32.84
	{0x51, 0xf8}, 	// Duty cycle = 32.93
	{0x46, 0xd6}, 	// Duty cycle = 33.02
	{0x31, 0x96}, 	// Duty cycle = 33.11
	{0x51, 0xf6}, 	// Duty cycle = 33.20
	{0x54, 0xfe}, 	// Duty cycle = 33.33
	{0x54, 0xfd}, 	// Duty cycle = 33.46
	{0x52, 0xf7}, 	// Duty cycle = 33.47
	{0x31, 0x94}, 	// Duty cycle = 33.56
	{0x46, 0xd2}, 	// Duty cycle = 33.65
	{0x53, 0xf8}, 	// Duty cycle = 33.73
	{0x43, 0xc8}, 	// Duty cycle = 33.83
	{0x39, 0xaa}, 	// Duty cycle = 33.92
	{0x53, 0xf6}, 	// Duty cycle = 34.01
	{0x49, 0xd8}, 	// Duty cycle = 34.10
	{0x42, 0xc3}, 	// Duty cycle = 34.18
	{0x48, 0xd4}, 	// Duty cycle = 34.27
	{0x4d, 0xe2}, 	// Duty cycle = 34.36
	{0x51, 0xed}, 	// Duty cycle = 34.45
	{0x4b, 0xdb}, 	// Duty cycle = 34.55
	{0x4f, 0xe6}, 	// Duty cycle = 34.63
	{0x4a, 0xd7}, 	// Duty cycle = 34.72
	{0x36, 0x9d}, 	// Duty cycle = 34.81
	{0x33, 0x94}, 	// Duty cycle = 34.90
	{0x53, 0xef}, 	// Duty cycle = 35.00
	{0x42, 0xbe}, 	// Duty cycle = 35.08
	{0x52, 0xeb}, 	// Duty cycle = 35.17
	{0x36, 0x9b}, 	// Duty cycle = 35.26
	{0x51, 0xe7}, 	// Duty cycle = 35.34
	{0x48, 0xcd}, 	// Duty cycle = 35.44
	{0x50, 0xe3}, 	// Duty cycle = 35.53
	{0x4d, 0xda}, 	// Duty cycle = 35.62
	{0x59, 0xfb}, 	// Duty cycle = 35.71
	{0x3e, 0xaf}, 	// Duty cycle = 35.80
	{0x3c, 0xa9}, 	// Duty cycle = 35.88
	{0x31, 0x8a}, 	// Duty cycle = 35.97
	{0x57, 0xf3}, 	// Duty cycle = 36.07
	{0x4c, 0xd4}, 	// Duty cycle = 36.15
	{0x35, 0x94}, 	// Duty cycle = 36.24
	{0x5b, 0xfc}, 	// Duty cycle = 36.36
	{0x3a, 0xa1}, 	// Duty cycle = 36.42
	{0x5b, 0xfb}, 	// Duty cycle = 36.51
	{0x46, 0xc1}, 	// Duty cycle = 36.60
	{0x3d, 0xa8}, 	// Duty cycle = 36.69
	{0x58, 0xf1}, 	// Duty cycle = 36.78
	{0x4f, 0xd8}, 	// Duty cycle = 36.87
	{0x54, 0xe5}, 	// Duty cycle = 36.96
	{0x5c, 0xfa}, 	// Duty cycle = 37.05
	{0x5a, 0xf4}, 	// Duty cycle = 37.14
	{0x32, 0x88}, 	// Duty cycle = 37.23
	{0x4a, 0xc8}, 	// Duty cycle = 37.31
	{0x30, 0x82}, 	// Duty cycle = 37.40
	{0x5c, 0xf7}, 	// Duty cycle = 37.50
	{0x37, 0x94}, 	// Duty cycle = 37.58
	{0x36, 0x91}, 	// Duty cycle = 37.67
	{0x35, 0x8e}, 	// Duty cycle = 37.76
	{0x50, 0xd5}, 	// Duty cycle = 37.85
	{0x5f, 0xfc}, 	// Duty cycle = 37.94
	{0x50, 0xd4}, 	// Duty cycle = 38.03
	{0x4c, 0xc9}, 	// Duty cycle = 38.12
	{0x50, 0xd3}, 	// Duty cycle = 38.21
	{0x59, 0xea}, 	// Duty cycle = 38.30
	{0x50, 0xd2}, 	// Duty cycle = 38.39
	{0x60, 0xfb}, 	// Duty cycle = 38.49
	{0x55, 0xde}, 	// Duty cycle = 38.57
	{0x5b, 0xed}, 	// Duty cycle = 38.66
	{0x49, 0xbe}, 	// Duty cycle = 38.74
	{0x4f, 0xcd}, 	// Duty cycle = 38.83
	{0x39, 0x94}, 	// Duty cycle = 38.93
	{0x56, 0xde}, 	// Duty cycle = 39.01
	{0x3c, 0x9b}, 	// Duty cycle = 39.10
	{0x4d, 0xc6}, 	// Duty cycle = 39.20
	{0x62, 0xfb}, 	// Duty cycle = 39.29
	{0x63, 0xfd}, 	// Duty cycle = 39.37
	{0x48, 0xb8}, 	// Duty cycle = 39.46
	{0x34, 0x85}, 	// Duty cycle = 39.55
	{0x57, 0xdd}, 	// Duty cycle = 39.64
	{0x58, 0xdf}, 	// Duty cycle = 39.73
	{0x57, 0xdc}, 	// Duty cycle = 39.82
	{0x56, 0xd9}, 	// Duty cycle = 39.91
	{0x65, 0xfe}, 	// Duty cycle = 40.00
	{0x5c, 0xe7}, 	// Duty cycle = 40.09
	{0x5b, 0xe4}, 	// Duty cycle = 40.17
	{0x5a, 0xe1}, 	// Duty cycle = 40.27
	{0x59, 0xde}, 	// Duty cycle = 40.36
	{0x5a, 0xe0}, 	// Duty cycle = 40.44
	{0x59, 0xdd}, 	// Duty cycle = 40.54
	{0x5a, 0xdf}, 	// Duty cycle = 40.62
	{0x66, 0xfc}, 	// Duty cycle = 40.71
	{0x46, 0xad}, 	// Duty cycle = 40.80
	{0x64, 0xf6}, 	// Duty cycle = 40.89
	{0x63, 0xf3}, 	// Duty cycle = 40.98
	{0x5b, 0xdf}, 	// Duty cycle = 41.07
	{0x68, 0xfe}, 	// Duty cycle = 41.18
	{0x62, 0xef}, 	// Duty cycle = 41.25
	{0x68, 0xfd}, 	// Duty cycle = 41.34
	{0x56, 0xd1}, 	// Duty cycle = 41.43
	{0x5c, 0xdf}, 	// Duty cycle = 41.52
	{0x38, 0x88}, 	// Duty cycle = 41.61
	{0x66, 0xf6}, 	// Duty cycle = 41.70
	{0x53, 0xc8}, 	// Duty cycle = 41.79
	{0x42, 0x9f}, 	// Duty cycle = 41.88
	{0x5d, 0xdf}, 	// Duty cycle = 41.96
	{0x59, 0xd5}, 	// Duty cycle = 42.06
	{0x3a, 0x8b}, 	// Duty cycle = 42.14
	{0x56, 0xcd}, 	// Duty cycle = 42.23
	{0x65, 0xf0}, 	// Duty cycle = 42.32
	{0x5e, 0xdf}, 	// Duty cycle = 42.41
	{0x65, 0xef}, 	// Duty cycle = 42.50
	{0x5b, 0xd7}, 	// Duty cycle = 42.59
	{0x68, 0xf5}, 	// Duty cycle = 42.68
	{0x46, 0xa5}, 	// Duty cycle = 42.77
	{0x6c, 0xfd}, 	// Duty cycle = 42.91
	{0x42, 0x9b}, 	// Duty cycle = 42.95
	{0x65, 0xec}, 	// Duty cycle = 43.04
	{0x5a, 0xd2}, 	// Duty cycle = 43.13
	{0x55, 0xc6}, 	// Duty cycle = 43.22
	{0x6d, 0xfd}, 	// Duty cycle = 43.31
	{0x5b, 0xd3}, 	// Duty cycle = 43.40
	{0x6a, 0xf5}, 	// Duty cycle = 43.50
	{0x4d, 0xb2}, 	// Duty cycle = 43.58
	{0x63, 0xe4}, 	// Duty cycle = 43.67
	{0x6c, 0xf8}, 	// Duty cycle = 43.78
	{0x58, 0xca}, 	// Duty cycle = 43.84
	{0x68, 0xee}, 	// Duty cycle = 43.93
	{0x50, 0xb7}, 	// Duty cycle = 44.02
	{0x68, 0xed}, 	// Duty cycle = 44.12
	{0x3c, 0x89}, 	// Duty cycle = 44.20
	{0x60, 0xda}, 	// Duty cycle = 44.29
	{0x4a, 0xa8}, 	// Duty cycle = 44.38
	{0x70, 0xfd}, 	// Duty cycle = 44.49
	{0x55, 0xc0}, 	// Duty cycle = 44.56
	{0x5f, 0xd6}, 	// Duty cycle = 44.65
	{0x65, 0xe3}, 	// Duty cycle = 44.74
	{0x67, 0xe7}, 	// Duty cycle = 44.83
	{0x69, 0xeb}, 	// Duty cycle = 44.92
	{0x70, 0xfa}, 	// Duty cycle = 45.02
	{0x72, 0xfe}, 	// Duty cycle = 45.10
	{0x3c, 0x86}, 	// Duty cycle = 45.19
	{0x5a, 0xc8}, 	// Duty cycle = 45.27
	{0x5c, 0xcc}, 	// Duty cycle = 45.37
	{0x72, 0xfc}, 	// Duty cycle = 45.45
	{0x5b, 0xc9}, 	// Duty cycle = 45.54
	{0x5d, 0xcd}, 	// Duty cycle = 45.63
	{0x6a, 0xe9}, 	// Duty cycle = 45.73
	{0x51, 0xb2}, 	// Duty cycle = 45.81
	{0x6f, 0xf3}, 	// Duty cycle = 45.90
	{0x55, 0xba}, 	// Duty cycle = 45.99
	{0x5d, 0xcb}, 	// Duty cycle = 46.08
	{0x72, 0xf8}, 	// Duty cycle = 46.18
	{0x43, 0x92}, 	// Duty cycle = 46.26
	{0x6b, 0xe8}, 	// Duty cycle = 46.35
	{0x6e, 0xee}, 	// Duty cycle = 46.44
	{0x42, 0x8f}, 	// Duty cycle = 46.53
	{0x3d, 0x84}, 	// Duty cycle = 46.62
	{0x4d, 0xa6}, 	// Duty cycle = 46.71
	{0x48, 0x9b}, 	// Duty cycle = 46.79
	{0x70, 0xf0}, 	// Duty cycle = 46.89
	{0x64, 0xd6}, 	// Duty cycle = 46.98
	{0x70, 0xef}, 	// Duty cycle = 47.08
	{0x73, 0xf5}, 	// Duty cycle = 47.15
	{0x77, 0xfd}, 	// Duty cycle = 47.24
	{0x46, 0x95}, 	// Duty cycle = 47.33
	{0x5b, 0xc1}, 	// Duty cycle = 47.42
	{0x68, 0xdc}, 	// Duty cycle = 47.51
	{0x6c, 0xe4}, 	// Duty cycle = 47.60
	{0x5c, 0xc2}, 	// Duty cycle = 47.69
	{0x55, 0xb3}, 	// Duty cycle = 47.78
	{0x64, 0xd2}, 	// Duty cycle = 47.87
	{0x5d, 0xc3}, 	// Duty cycle = 47.96
	{0x6e, 0xe6}, 	// Duty cycle = 48.05
	{0x74, 0xf2}, 	// Duty cycle = 48.15
	{0x43, 0x8c}, 	// Duty cycle = 48.23
	{0x55, 0xb1}, 	// Duty cycle = 48.31
	{0x5a, 0xbb}, 	// Duty cycle = 48.40
	{0x70, 0xe8}, 	// Duty cycle = 48.50
	{0x77, 0xf6}, 	// Duty cycle = 48.58
	{0x6d, 0xe1}, 	// Duty cycle = 48.67
	{0x4e, 0xa1}, 	// Duty cycle = 48.77
	{0x54, 0xad}, 	// Duty cycle = 48.85
	{0x73, 0xec}, 	// Duty cycle = 48.95
	{0x64, 0xcd}, 	// Duty cycle = 49.03
	{0x6f, 0xe3}, 	// Duty cycle = 49.12
	{0x7c, 0xfd}, 	// Duty cycle = 49.21
	{0x69, 0xd6}, 	// Duty cycle = 49.30
	{0x78, 0xf4}, 	// Duty cycle = 49.39
	{0x5e, 0xbf}, 	// Duty cycle = 49.48
	{0x72, 0xe7}, 	// Duty cycle = 49.57
	{0x47, 0x90}, 	// Duty cycle = 49.66
	{0x61, 0xc4}, 	// Duty cycle = 49.75
	{0x7e, 0xfd}, 	// Duty cycle = 50.00
	{0x7e, 0xfd}, 	// Duty cycle = 50.00
	{0x7f, 0xfe}, 	// Duty cycle = 50.20
	{0x7f, 0xfe}, 	// Duty cycle = 50.20
	{0x7f, 0xfe}, 	// Duty cycle = 50.20
	{0x58, 0xb0}, 	// Duty cycle = 50.28
	{0x42, 0x84}, 	// Duty cycle = 50.38
	{0x6c, 0xd7}, 	// Duty cycle = 50.46
	{0x5b, 0xb5}, 	// Duty cycle = 50.55
	{0x4e, 0x9b}, 	// Duty cycle = 50.64
	{0x67, 0xcc}, 	// Duty cycle = 50.73
	{0x7b, 0xf3}, 	// Duty cycle = 50.82
	{0x6f, 0xdb}, 	// Duty cycle = 50.91
	{0x65, 0xc7}, 	// Duty cycle = 51.00
	{0x5d, 0xb7}, 	// Duty cycle = 51.09
	{0x56, 0xa9}, 	// Duty cycle = 51.18
	{0x50, 0x9d}, 	// Duty cycle = 51.27
	{0x70, 0xdb}, 	// Duty cycle = 51.36
	{0x58, 0xac}, 	// Duty cycle = 51.45
	{0x53, 0xa2}, 	// Duty cycle = 51.53
	{0x7e, 0xf5}, 	// Duty cycle = 51.63
	{0x77, 0xe7}, 	// Duty cycle = 51.72
	{0x72, 0xdd}, 	// Duty cycle = 51.80
	{0x5f, 0xb8}, 	// Duty cycle = 51.89
	{0x75, 0xe2}, 	// Duty cycle = 51.98
	{0x57, 0xa8}, 	// Duty cycle = 52.07
	{0x83, 0xfc}, 	// Duty cycle = 52.17
	{0x73, 0xdd}, 	// Duty cycle = 52.25
	{0x7a, 0xea}, 	// Duty cycle = 52.34
	{0x60, 0xb8}, 	// Duty cycle = 52.43
	{0x48, 0x8a}, 	// Duty cycle = 52.52
	{0x6e, 0xd2}, 	// Duty cycle = 52.61
	{0x7e, 0xf0}, 	// Duty cycle = 52.70
	{0x7a, 0xe8}, 	// Duty cycle = 52.79
	{0x64, 0xbe}, 	// Duty cycle = 52.88
	{0x85, 0xfc}, 	// Duty cycle = 52.96
	{0x81, 0xf4}, 	// Duty cycle = 53.06
	{0x4b, 0x8e}, 	// Duty cycle = 53.15
	{0x6a, 0xc8}, 	// Duty cycle = 53.23
	{0x87, 0xfe}, 	// Duty cycle = 53.33
	{0x84, 0xf8}, 	// Duty cycle = 53.41
	{0x53, 0x9c}, 	// Duty cycle = 53.50
	{0x60, 0xb4}, 	// Duty cycle = 53.59
	{0x65, 0xbd}, 	// Duty cycle = 53.68
	{0x71, 0xd3}, 	// Duty cycle = 53.77
	{0x83, 0xf4}, 	// Duty cycle = 53.88
	{0x73, 0xd6}, 	// Duty cycle = 53.95
	{0x6a, 0xc5}, 	// Duty cycle = 54.04
	{0x75, 0xd9}, 	// Duty cycle = 54.13
	{0x86, 0xf8}, 	// Duty cycle = 54.22
	{0x7d, 0xe7}, 	// Duty cycle = 54.31
	{0x62, 0xb5}, 	// Duty cycle = 54.40
	{0x54, 0x9b}, 	// Duty cycle = 54.49
	{0x88, 0xfa}, 	// Duty cycle = 54.58
	{0x7a, 0xe0}, 	// Duty cycle = 54.67
	{0x89, 0xfb}, 	// Duty cycle = 54.76
	{0x81, 0xec}, 	// Duty cycle = 54.85
	{0x7f, 0xe8}, 	// Duty cycle = 54.94
	{0x7d, 0xe4}, 	// Duty cycle = 55.02
	{0x7b, 0xe0}, 	// Duty cycle = 55.11
	{0x79, 0xdc}, 	// Duty cycle = 55.20
	{0x8c, 0xfe}, 	// Duty cycle = 55.29
	{0x6b, 0xc2}, 	// Duty cycle = 55.38
	{0x46, 0x7f}, 	// Duty cycle = 55.47
	{0x8a, 0xf9}, 	// Duty cycle = 55.60
	{0x84, 0xee}, 	// Duty cycle = 55.65
	{0x87, 0xf3}, 	// Duty cycle = 55.74
	{0x5a, 0xa2}, 	// Duty cycle = 55.83
	{0x88, 0xf4}, 	// Duty cycle = 55.92
	{0x86, 0xf0}, 	// Duty cycle = 56.02
	{0x89, 0xf5}, 	// Duty cycle = 56.10
	{0x6c, 0xc1}, 	// Duty cycle = 56.19
	{0x8a, 0xf6}, 	// Duty cycle = 56.28
	{0x7b, 0xdb}, 	// Duty cycle = 56.36
	{0x75, 0xd0}, 	// Duty cycle = 56.46
	{0x78, 0xd5}, 	// Duty cycle = 56.54
	{0x6e, 0xc3}, 	// Duty cycle = 56.63
	{0x86, 0xed}, 	// Duty cycle = 56.72
	{0x7c, 0xdb}, 	// Duty cycle = 56.82
	{0x87, 0xee}, 	// Duty cycle = 56.90
	{0x69, 0xb9}, 	// Duty cycle = 56.99
	{0x80, 0xe1}, 	// Duty cycle = 57.08
	{0x8e, 0xf9}, 	// Duty cycle = 57.20
	{0x8d, 0xf7}, 	// Duty cycle = 57.26
	{0x74, 0xcb}, 	// Duty cycle = 57.35
	{0x8a, 0xf1}, 	// Duty cycle = 57.44
	{0x6a, 0xb9}, 	// Duty cycle = 57.53
	{0x56, 0x96}, 	// Duty cycle = 57.62
	{0x91, 0xfc}, 	// Duty cycle = 57.71
	{0x7d, 0xd9}, 	// Duty cycle = 57.80
	{0x8e, 0xf6}, 	// Duty cycle = 57.89
	{0x6c, 0xbb}, 	// Duty cycle = 57.98
	{0x8f, 0xf7}, 	// Duty cycle = 58.06
	{0x6a, 0xb7}, 	// Duty cycle = 58.15
	{0x69, 0xb5}, 	// Duty cycle = 58.24
	{0x92, 0xfb}, 	// Duty cycle = 58.33
	{0x6e, 0xbd}, 	// Duty cycle = 58.42
	{0x6d, 0xbb}, 	// Duty cycle = 58.51
	{0x6c, 0xb9}, 	// Duty cycle = 58.60
	{0x86, 0xe5}, 	// Duty cycle = 58.70
	{0x4c, 0x82}, 	// Duty cycle = 58.78
	{0x91, 0xf7}, 	// Duty cycle = 58.87
	{0x65, 0xac}, 	// Duty cycle = 58.96
	{0x7b, 0xd1}, 	// Duty cycle = 59.05
	{0x6d, 0xb9}, 	// Duty cycle = 59.14
	{0x89, 0xe8}, 	// Duty cycle = 59.23
	{0x8b, 0xeb}, 	// Duty cycle = 59.32
	{0x77, 0xc9}, 	// Duty cycle = 59.41
	{0x8c, 0xec}, 	// Duty cycle = 59.49
	{0x8e, 0xef}, 	// Duty cycle = 59.58
	{0x93, 0xf7}, 	// Duty cycle = 59.68
	{0x64, 0xa8}, 	// Duty cycle = 59.76
	{0x51, 0x88}, 	// Duty cycle = 59.85
	{0x98, 0xfe}, 	// Duty cycle = 60.00
	{0x97, 0xfc}, 	// Duty cycle = 60.08
	{0x61, 0xa2}, 	// Duty cycle = 60.12
	{0x72, 0xbe}, 	// Duty cycle = 60.21
	{0x77, 0xc6}, 	// Duty cycle = 60.30
	{0x5c, 0x99}, 	// Duty cycle = 60.39
	{0x64, 0xa6}, 	// Duty cycle = 60.48
	{0x94, 0xf5}, 	// Duty cycle = 60.57
	{0x7f, 0xd2}, 	// Duty cycle = 60.66
	{0x81, 0xd5}, 	// Duty cycle = 60.75
	{0x56, 0x8e}, 	// Duty cycle = 60.84
	{0x5b, 0x96}, 	// Duty cycle = 60.93
	{0x8f, 0xeb}, 	// Duty cycle = 61.02
	{0x99, 0xfb}, 	// Duty cycle = 61.11
	{0x7a, 0xc8}, 	// Duty cycle = 61.19
	{0x97, 0xf7}, 	// Duty cycle = 61.29
	{0x8e, 0xe8}, 	// Duty cycle = 61.37
	{0x7d, 0xcc}, 	// Duty cycle = 61.46
	{0x9c, 0xfe}, 	// Duty cycle = 61.57
	{0x86, 0xda}, 	// Duty cycle = 61.64
	{0x78, 0xc3}, 	// Duty cycle = 61.73
	{0x94, 0xf0}, 	// Duty cycle = 61.83
	{0x93, 0xee}, 	// Duty cycle = 61.92
	{0x9a, 0xf9}, 	// Duty cycle = 62.00
	{0x70, 0xb5}, 	// Duty cycle = 62.09
	{0x60, 0x9b}, 	// Duty cycle = 62.18
	{0x88, 0xdb}, 	// Duty cycle = 62.27
	{0x6e, 0xb1}, 	// Duty cycle = 62.36
	{0x8e, 0xe4}, 	// Duty cycle = 62.45
	{0x9c, 0xfa}, 	// Duty cycle = 62.55
	{0x7b, 0xc5}, 	// Duty cycle = 62.63
	{0x8e, 0xe3}, 	// Duty cycle = 62.72
	{0x66, 0xa3}, 	// Duty cycle = 62.80
	{0x63, 0x9e}, 	// Duty cycle = 62.89
	{0x71, 0xb4}, 	// Duty cycle = 62.98
	{0x7a, 0xc2}, 	// Duty cycle = 63.08
	{0x96, 0xee}, 	// Duty cycle = 63.18
	{0x68, 0xa5}, 	// Duty cycle = 63.25
	{0x9e, 0xfa}, 	// Duty cycle = 63.35
	{0x54, 0x85}, 	// Duty cycle = 63.43
	{0x93, 0xe8}, 	// Duty cycle = 63.52
	{0xa0, 0xfc}, 	// Duty cycle = 63.64
	{0x5c, 0x91}, 	// Duty cycle = 63.70
	{0x93, 0xe7}, 	// Duty cycle = 63.79
	{0x90, 0xe2}, 	// Duty cycle = 63.88
	{0x9d, 0xf6}, 	// Duty cycle = 63.97
	{0x8a, 0xd8}, 	// Duty cycle = 64.06
	{0x87, 0xd3}, 	// Duty cycle = 64.15
	{0x60, 0x96}, 	// Duty cycle = 64.24
	{0x76, 0xb8}, 	// Duty cycle = 64.32
	{0x8e, 0xdd}, 	// Duty cycle = 64.41
	{0x94, 0xe6}, 	// Duty cycle = 64.50
	{0x86, 0xd0}, 	// Duty cycle = 64.59
	{0x97, 0xea}, 	// Duty cycle = 64.68
	{0x71, 0xaf}, 	// Duty cycle = 64.77
	{0x8f, 0xdd}, 	// Duty cycle = 64.86
	{0x8a, 0xd5}, 	// Duty cycle = 64.95
	{0x9f, 0xf5}, 	// Duty cycle = 65.04
	{0x7e, 0xc2}, 	// Duty cycle = 65.13
	{0x97, 0xe8}, 	// Duty cycle = 65.24
	{0x90, 0xdd}, 	// Duty cycle = 65.32
	{0x9a, 0xec}, 	// Duty cycle = 65.40
	{0x93, 0xe1}, 	// Duty cycle = 65.49
	{0x8c, 0xd6}, 	// Duty cycle = 65.58
	{0x98, 0xe8}, 	// Duty cycle = 65.67
	{0x78, 0xb7}, 	// Duty cycle = 65.76
	{0x9f, 0xf2}, 	// Duty cycle = 65.84
	{0x77, 0xb5}, 	// Duty cycle = 65.93
	{0x66, 0x9b}, 	// Duty cycle = 66.03
	{0x9f, 0xf1}, 	// Duty cycle = 66.12
	{0x8e, 0xd7}, 	// Duty cycle = 66.20
	{0x75, 0xb1}, 	// Duty cycle = 66.29
	{0x9b, 0xea}, 	// Duty cycle = 66.38
	{0x70, 0xa9}, 	// Duty cycle = 66.47
	{0xa9, 0xfe}, 	// Duty cycle = 66.67
	{0xa9, 0xfe}, 	// Duty cycle = 66.67
	{0xa8, 0xfc}, 	// Duty cycle = 66.80
	{0x88, 0xcc}, 	// Duty cycle = 66.83
	{0x58, 0x84}, 	// Duty cycle = 66.92
	{0x81, 0xc1}, 	// Duty cycle = 67.01
	{0x67, 0x9a}, 	// Duty cycle = 67.10
	{0x80, 0xbf}, 	// Duty cycle = 67.19
	{0x91, 0xd8}, 	// Duty cycle = 67.28
	{0xa0, 0xee}, 	// Duty cycle = 67.36
	{0x71, 0xa8}, 	// Duty cycle = 67.46
	{0x99, 0xe3}, 	// Duty cycle = 67.54
	{0x8b, 0xce}, 	// Duty cycle = 67.63
	{0x7f, 0xbc}, 	// Duty cycle = 67.72
	{0x75, 0xad}, 	// Duty cycle = 67.82
	{0xa4, 0xf2}, 	// Duty cycle = 67.90
	{0xa9, 0xf9}, 	// Duty cycle = 68.00
	{0x9f, 0xea}, 	// Duty cycle = 68.09
	{0xa4, 0xf1}, 	// Duty cycle = 68.18
	{0x9c, 0xe5}, 	// Duty cycle = 68.26
	{0x94, 0xd9}, 	// Duty cycle = 68.35
	{0xa6, 0xf3}, 	// Duty cycle = 68.44
	{0x86, 0xc4}, 	// Duty cycle = 68.53
	{0x80, 0xbb}, 	// Duty cycle = 68.62
	{0x64, 0x92}, 	// Duty cycle = 68.71
	{0xab, 0xf9}, 	// Duty cycle = 68.80
	{0x9a, 0xe0}, 	// Duty cycle = 68.89
	{0xa8, 0xf4}, 	// Duty cycle = 68.98
	{0x5f, 0x8a}, 	// Duty cycle = 69.06
	{0x8a, 0xc8}, 	// Duty cycle = 69.15
	{0xa8, 0xf3}, 	// Duty cycle = 69.26
	{0x9b, 0xe0}, 	// Duty cycle = 69.33
	{0xa7, 0xf1}, 	// Duty cycle = 69.42
	{0xaa, 0xf5}, 	// Duty cycle = 69.51
	{0xad, 0xf9}  	// Duty cycle = 69.60
};

const uint8_t NTC_LOOKUP[33] PROGMEM = {
		0x00, 	// ADC=0, Temperature=0
		0x04, 	// ADC=32, Temperature=4
		0x13, 	// ADC=64, Temperature=19
		0x1d, 	// ADC=96, Temperature=29
		0x24, 	// ADC=128, Temperature=36
		0x2b, 	// ADC=160, Temperature=43
		0x31, 	// ADC=192, Temperature=49
		0x36, 	// ADC=224, Temperature=54
		0x3b, 	// ADC=256, Temperature=59
		0x3f, 	// ADC=288, Temperature=63
		0x43, 	// ADC=320, Temperature=67
		0x48, 	// ADC=352, Temperature=72
		0x4c, 	// ADC=384, Temperature=76
		0x50, 	// ADC=416, Temperature=80
		0x54, 	// ADC=448, Temperature=84
		0x58, 	// ADC=480, Temperature=88
		0x5c, 	// ADC=512, Temperature=92
		0x60, 	// ADC=544, Temperature=96
		0x64, 	// ADC=576, Temperature=100
		0x68, 	// ADC=608, Temperature=104
		0x6d, 	// ADC=640, Temperature=109
		0x72, 	// ADC=672, Temperature=114
		0x77, 	// ADC=704, Temperature=119
		0x7c, 	// ADC=736, Temperature=124
		0x82, 	// ADC=768, Temperature=130
		0x88, 	// ADC=800, Temperature=136
		0x8f, 	// ADC=832, Temperature=143
		0x97, 	// ADC=864, Temperature=151
		0xa0, 	// ADC=896, Temperature=160
		0xab, 	// ADC=928, Temperature=171
		0xb9, 	// ADC=960, Temperature=185
		0xcc, 	// ADC=992, Temperature=204
		0xe9 	// ADC=1024, Temperature=233
};

void boost_Init() {
	/* setup PWM on OC0B (PA7) */
	/* initially set pin low -> FET is off */
	PORTA &= ~(1 << PA7);
	DDRA |= (1 << PA7);

	/* initialize default voltage/current limits */
	boost_setCurrent(BOOST_INITIAL_CURRENT);
	boost_setMaxVoltage(BOOST_INITIAL_VOLTAGE);
	boost_setMaxTemperature(BOOST_INITIAL_TEMPLIMIT);

	/* copy initial limits into USI registers */
	usi.ledData.setCurrent = boost.setCurrent;
	usi.ledData.setVoltage = boost.setVoltage;
	usi.ledData.tempLimit = boost.maxTemp;

	boost.isEnabled = 0;
	boost.active = 0;
}

void boost_Enable() {
	/* initialize PWM value, start with lowest PWM value */
	boost.dutyCycleIt = 0;
	boost_updatePWM();
	/* set non-inverting fast PWM mode, using OCR0A as TOP */
	TCCR0A |= (1 << COM0B1) | (1 << WGM01) | (1 << WGM00);
	/* set PWM as fast as possible, results in 78kHz PWM frequency */
	TCCR0B |= (1 << CS00) | (1 << WGM02);
	boost.isEnabled = 1;
}

void boost_Disable() {
	/* set pin low -> FET is off (should already be low, just a safety measure) */
	PORTA &= ~(1 << PA7);
	DDRA |= (1 << PA7);
	/* disable PWM */
	TCCR0A = TCCR0B = 0;
	OCR0A = OCR0B = 0;
	boost.dutyCycleIt = 0;
	boost.isEnabled = 0;
}

void boost_Update(void) {
	/* calculate values from raw ADC data */
	boost.current = (adc.raw[ADC_CURRENT] * 100000UL)
			/ (93UL * BOOST_SHUNT_VALUE);
	boost.voltage = (adc.raw[ADC_VOLTAGE] * 100UL * BOOST_VOL_SENS_FACT) / 93;

	/* interpolate temperature from lookup-table */
	uint8_t index = adc.raw[ADC_TEMPERATURE] / 32;
	uint8_t interpolate = adc.raw[ADC_TEMPERATURE] % 32;
	static uint16_t tempAvg = 0;
	tempAvg += pgm_read_byte(&NTC_LOOKUP[index]);
	tempAvg += (pgm_read_byte(&NTC_LOOKUP[index + 1])
			- pgm_read_byte(&NTC_LOOKUP[index])) * interpolate / 32;
	boost.temperature = tempAvg >> 8;
	tempAvg -= boost.temperature;

	if (!boost.isEnabled && boost.active
			&& (boost.maxTemp >= boost.temperature + 5)) {
		/* was disabled, now active and temperature is OK */
		boost_Enable();
	} else if (boost.isEnabled
			&& (!boost.active || (boost.maxTemp < boost.temperature))) {
		/* was active, now disabled or temperature too hot */
		boost_Disable();
	}
	if (boost.isEnabled) {
		if (boost.voltage > boost.setVoltage) {
			/* voltage at limit -> decrease duty cycle */
			boost.dutyCycleIt--;
		} else {
			/* voltage not at limit -> control current */
			int16_t currDiff = boost.setCurrent - boost.current;
			/* change duty cycle */
			int16_t change = currDiff / 5;
			if (change > 5) {
				change = 5;
			} else if (change < -5) {
				change = -5;
			}
			boost.dutyCycleIt += change;
		}
		if (boost.dutyCycleIt < 0)
			boost.dutyCycleIt = 0;
		else if (boost.dutyCycleIt > (int16_t) (sizeof(PWM_LOOKUP) / 2 - 1))
			boost.dutyCycleIt = sizeof(PWM_LOOKUP) / 2 - 1;
		boost_updatePWM();
	}
}

void boost_setCurrent(uint16_t mA) {
	if (mA > BOOST_MAX_CURRENT)
		/* limit current to maximum */
		mA = BOOST_MAX_CURRENT;
	boost.setCurrent = mA;
}

void boost_setMaxVoltage(uint16_t mV) {
	if (mV > BOOST_MAX_VOLTAGE)
		/* limit voltage to maximum */
		mV = BOOST_MAX_VOLTAGE;
	boost.setVoltage = mV;
}

void boost_setMaxTemperature(uint8_t deg) {
	boost.maxTemp = deg;
}

void boost_updatePWM(void) {
	/* extract PWM generation values and store in registers */
	OCR0B = pgm_read_byte(&PWM_LOOKUP[boost.dutyCycleIt][0]);
	OCR0A = pgm_read_byte(&PWM_LOOKUP[boost.dutyCycleIt][1]);
}
